### ISSUE TITLE
Bot digs faster than a player from the launcher

### ISSUE THREAD

**Issue by flymer5** [PrismarineJS/mineflayer#1313] opened 2020-09-13 15:26 UTC
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.28.1
 - server: vanilla/spigot/paper 1.13.2
 - node: 12.18.3

## Detailed description of a problem
A bot with a pick with an efficiency of 5 digs faster than a player with a launcher with the same pick. What could be the problem?

## What did you try yet?

bot.dig()
bot.blockInsight()
bot.targetDigBlock
## Your current code
```js

const dig = () => {
				if (digging == 1 ) {
					if (bot.targetDigBlock) {
						setTimeout(dig, 1)
						return
					}else{
						var target = bot.blockInSight()
						if (target !== undefined && target.position.distanceTo(bot.entity.position) > 7) {
							target = undefined
						};
						if (target !== undefined) {
							bot.dig(target,() => setTimeout(dig, 1));
						}else{
							setTimeout(dig, 1)
							return
						}
					}
				}
			};

```

## Additional context

**Comment by Karang** [comment] 2020-09-13 15:28
Duplicate of https://github.com/PrismarineJS/mineflayer/issues/1307 reopen the first one if it is not solved.

**Closed by Karang** 2020-09-13 15:28 UTC
Labels: possible bug

**Comment by flymer5** [comment] 2020-09-14 04:15
> Duplicate of #1307 reopen the first one if it is not solved.

But they are different! In that I talked about the slowness of digging until I switched to 1.13.2. Now I noticed that at 1.13.2 a bot with an efficiency of 5 digs faster than the player
