### ISSUE TITLE
Faster Crafting

### ISSUE THREAD

**Issue by hexatester** [PrismarineJS/mineflayer#1033] opened 2020-06-05 15:08 UTC
## Is your feature request related to a problem? Please describe.
When i craft many quantity of item, eg
`bot.craft(paperRecipe, 9 * 64, true, err => console.error(err))`
Its seems like the bot open and close craftingbench each craft.

And 1x craft = 1x recipe of paper (3 paper), instead of maximum amount result per craft which is 64x recipe (64 x 3 paper).

## Describe the solution you'd like
Add craftStack method?

Pseudo code
```
Open craftingbench
If recipe stackable
  do craftStack for Math.floor(amount / 64)
  if (amount % 64 > 0) do craft for amount % 64 > 0
else 
  do craft for amount
Close craftingbench
```

## Describe alternatives you've considered
Instead of open and close crafting bench each craft recipe,
We should open and close it once.

## Additional context
-

**Comment by rom1504** [comment] 2020-06-05 16:16
related https://github.com/PrismarineJS/mineflayer/issues/257

agreed this could be improved

**Comment by rom1504** [comment] 2020-08-30 17:33
duplicate of https://github.com/PrismarineJS/mineflayer/issues/257

**Closed by rom1504** 2020-08-30 17:33 UTC
Labels: new feature
