### ISSUE TITLE
Bots break on bungee servers - read error for undefined SkyLight

### ISSUE THREAD

**Issue by FantomHD** [PrismarineJS/mineflayer#651] opened 2018-03-13 01:47 UTC
Hey guys,

So I'm having the same problem it looks like a couple of people have had in the past... but I can't seem to fix it or find a clear answer.

To start with, the bot wont even connect to bungee hubs (on any version) without the change found in #462 But once I make that change, it will connect and work fine on the hub.

But, when I try to connect the bot to one of the sub servers, the bot throws an error "Read error for skyLight: undefined". Whole error thrown here: https://pastebin.com/Nsy0SMGX I've looked some more into this and it seemed at first like this was supposed to be a 1.8 only problem, as in one of the issues someone said it was fixed in 1.9, but it's obviously not fixed for me (I'm on 1.9.4, have tried different 1.9 versions, and it times out before even throwing this error on some versions above). The problem is more closely outlined in #565 and some other closely connected issues, but there hasn't been any further talk about it since.

The repo owner seems to be a little inactive in this project now, but if anyone else has any insight it would be great. Thanks for any help.

**Comment by rom1504** [comment] 2018-04-06 14:02
Look at the packets sent and received in your situation using DEBUG =
"minecraft-protocol" (see the doc) then check bungee code and compare. Then
adapt node-minecraft-protocol code to also works with bungee.

**Comment by unnown** [comment] 2018-04-23 09:05
i was having the same issue with mineflayer, weirdly enough it works fine 
when just using the protocol lib (and defining 1.12)

server:
play.riftmc.org

**Comment by plexigras** [comment] 2018-04-23 13:05
@unnown that is probably caused by the server not telling you the correct version.

**Comment by unnown** [comment] 2018-04-23 13:10
i would agree, but setting mineflayer to 1.12 still causes this bug

so protocol works fine with setting it to 1.12 on this server (you Have to set it)
mineflayer doesn't work, and comes up with this error

**Comment by unnown** [comment] 2018-04-24 13:17
-------------------------------------
deserializer
-------------------------------------
map_chunk
{ x: 0,
  z: 0,
  groundUp: true,
  bitMap: 40704,
  chunkData: <Buffer 04 02 00 10 80 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
  blockEntities: 
   [ { type: 'compound', name: '', value: [Object] },
     { type: 'compound', name: '', value: [Object] },
     { type: 'compound', name: '', value: [Object] },
     { type: 'compound', name: '', value: [Object] },
     { type: 'compound', name: '', value: [Object] } ] }
{ size: 28232, name: 'map_chunk', state: 'play' }
-------------------------------------
 
 
{ PartialReadError: Deserialization error for play.toClient : Read error for skyLight : undefined
    at PartialReadError.ExtendableError (node_modules\protodef\src\utils.js:75:11)
    at PartialReadError (node_modules\protodef\src\utils.js:81:5)
    at ProtoDef.readBuffer (node_modules\protodef\src\datatypes\utils.js:150:42)
    at ProtoDef.read (node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (node_modules\protodef\src\utils.js:63:16)
    at tryDoc (node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (node_modules\protodef\src\datatypes\structures.js:44:12)
  name: 'PartialReadError',
  message: 'Deserialization error for play.toClient : Read error for skyLight : undefined',
  partialReadError: true,
  field: 'play.toClient' }

**Comment by Legoburner73** [comment] 2018-05-06 17:58
Oh look! It's fixed now!
What i did to fix it: install debug module...

**Comment by rom1504** [comment] 2018-05-13 19:42
now fixed

**Closed by rom1504** 2018-05-13 19:42 UTC
Labels: non-vanilla, protocol support
