### ISSUE TITLE
support  skyLightSent in prismarine-chunk for 1.8

### ISSUE THREAD

**Issue by andre-paulo98** [PrismarineJS/mineflayer#565] opened 2017-07-15 12:39 UTC
Using MineFlayer to connect to a Bungee server i'm getting this crash as soon as i try to change server with command:
```
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:192
      throw(new Error(`Data buffer not correct size \(was ${data.length}, expected ${BUFFER_SIZE}\)`));
      ^

Error: Data buffer not correct size (was 164096, expected 196864)
    at Chunk.load (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:192:13)
    at addColumn (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\blocks.js:46:12)
    at Client.bot._client.on (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\blocks.js:187:7)
    at emitTwo (events.js:125:13)
    at Client.emit (events.js:213:7)
    at Parser.deserializer.on (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\node_modules\minecraft-protocol\src\client.js:102:12)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at addChunk (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_readable.js:271:11)
```
This is the code i'm using: 

```
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "server.ip",
  port: 25565,
  username: "email",
  password: "password",
  version: "1.8"
});
bot.on('spawn', function() {
    bot.chat("/server ruby");
});
```

Tried setting up a bungeecord locally with 2 servers and it worked.
Player logged in as bot has permissions to /server

**Comment by andre-paulo98** [comment] 2017-07-16 13:22
Got a log w/ debug:
https://gist.github.com/andre-paulo98/4af6716a87f54b21dfdacb7af12b22df

**Comment by rom1504** [comment] 2017-07-16 19:51
@andre-paulo98 which server is it ?
It seems like something that could be caused by something different the server is doing.

**Comment by andre-paulo98** [comment] 2017-07-17 01:24
The server is play.kastia.net
Other general console clients can join fine

**Comment by plexigras** [comment] 2017-07-17 10:02
If you have the newest version of mineflayer you can disable the internal blocks plugin by doing
```js
mineflayer.createBot({
  ...otherOptions,
  plugins:{
    blocks: false
  }
})
```

**Comment by rom1504** [comment] 2017-07-17 10:12
@plexigras if he does that then the bot will hang in the air and physics will be basically unavailable. But yeah it's possible.

I guess the problem might be that skylight is not sent in his server because they are using a world with the characteristics of the underworld.

Maybe prismarine-chunk should check the length of the buffer and assume there is no skylight if the buffer is that size.

**Comment by plexigras** [comment] 2017-07-17 10:57
@rom1504 the [`skyLightSent: false`](https://gist.github.com/andre-paulo98/4af6716a87f54b21dfdacb7af12b22df#file-gistfile1-txt-L7754) argument is handled in [`1.9`](https://github.com/PrismarineJS/prismarine-chunk/blob/8a0e223a48c4a837f47edd20a909f86143f2d573/src/pc/1.9/chunk.js#L342-L349) but not in [`1.8`](
https://github.com/PrismarineJS/prismarine-chunk/blob/8a0e223a48c4a837f47edd20a909f86143f2d573/src/pc/1.8/chunk.js#L172-L194).

**Comment by andre-paulo98** [comment] 2017-07-17 11:04
With blocks set to false it also crashes:
```
C:\Users\Utilizador\Desktop\mineflayer-master\mcbot>node index.js
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\physics.js:131
    const underBlock = bot.blockAt(pos.offset(0, -1, 0))
                           ^

TypeError: bot.blockAt is not a function
    at nextFrame (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\physics.js:131:28)

    at Timeout.doPhysics [as _onTimeout] (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\physics.js:53:5)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

**Comment by plexigras** [comment] 2017-07-17 11:06
also disable physics

**Comment by andre-paulo98** [comment] 2017-07-17 11:17
Still the same crash. 
```
C:\Users\Utilizador\Desktop\mineflayer-master\mcbot>node index.js
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\block_actions.js:10
    const block = bot.blockAt(pt)
                      ^
 
TypeError: bot.blockAt is not a function
    at Client.bot._client.on (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\lib\plugins\block_actions.js:10:23)
    at emitTwo (events.js:125:13)
    at Client.emit (events.js:213:7)
    at Parser.deserializer.on (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\mineflayer\node_modules\minecraft-protocol\src\client.js:102:12)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)

    at addChunk (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_readable.js:271:11)
    at Parser.Readable.push (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at Parser.Transform.push (C:\Users\Utilizador\Desktop\mineflayer-master\mcbot\node_modules\readable-stream\lib\_stream_transform.js:146:32)
```
var bot = mineflayer.createBot({
  host: "ip", // optional
  port: 25565,       // optional
  username: "e", // email and password are required only for
  password: "p",
  version: "1.8.7",
  plugins:{
   blocks: false,
   physics: false
 }
});
``

**Comment by plexigras** [comment] 2017-07-17 11:45
then disable the plugins that crash, in this case `block_actions`

**Comment by andre-paulo98** [comment] 2017-07-17 13:01
Hmm, chat got disabled so i can't send messages/commands
So i cant really test using the /server command

**Comment by rom1504** [comment] 2017-07-17 13:05
> chat got disabled
really, why ?

**Comment by plexigras** [comment] 2017-07-17 21:00
`chat got disabled` when doing what?

**Comment by andre-paulo98** [comment] 2017-07-17 23:34
After bit of testing, it was the bot.on('spawn')
Chat is still working.
I think this would work for now until someone fixes the bug on prismarine-chunk.
Thank you

**Comment by rom1504** [comment] 2017-07-18 07:07
that is a workaround, not a fix, I'll close this when the bug is fixed

**Comment by johnpyp** [comment] 2017-09-29 19:56
Getting a similar issue. Just started using mineflayer, and I had to use the work around found here: https://github.com/PrismarineJS/node-minecraft-protocol/issues/462

After a little bit of it working, I get this error: 
`D:\epcmuser\Desktop\Coding\HTML & Web Development\mineflayer-bot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:192    
      throw(new Error(`Data buffer not correct size \(was ${data.length}, expected ${BUFFER_SIZE}\)`));                   
      ^                                                                                                                   
                                                                                                                          
Error: Data buffer not correct size (was 196608, expected 196864)                                                         
    at Chunk.load (D:\epcmuser\Desktop\Coding\HTML & Web Development\mineflayer-bot\node_modules\prismarine-chunk\src\pc\1
.8\chunk.js:192:13)                                                                                                       
    at addColumn (D:\epcmuser\Desktop\Coding\HTML & Web Development\mineflayer-bot\node_modules\mineflayer\lib\plugins\blo
cks.js:46:12)                                                                                                             
    at Client.bot._client.on (D:\epcmuser\Desktop\Coding\HTML & Web Development\mineflayer-bot\node_modules\mineflayer\lib
\plugins\blocks.js:166:5)                                                                                                 
    at emitTwo (events.js:125:13)                                                                                         
    at Client.emit (events.js:213:7)                                                                                      
    at Parser.deserializer.on (D:\epcmuser\Desktop\Coding\HTML & Web Development\mineflayer-bot\node_modules\minecraft-pro
tocol\src\client.js:102:12)                                                                                               
    at emitOne (events.js:115:13)                                                                                         
    at Parser.emit (events.js:210:7)                                                                                      
    at addChunk (D:\epcmuser\Desktop\Coding\HTML & Web Development\mineflayer-bot\node_modules\readable-stream\lib\_stream
_readable.js:284:12)                                                                                                      
    at readableAddChunk (D:\epcmuser\Desktop\Coding\HTML & Web Development\mineflayer-bot\node_modules\readable-stream\lib
\_stream_readable.js:271:11)                                                                                              `

My program is just echo and bot.chat with a little bit of socket.io stuff to make a web interface.

**Comment by rom1504** [comment] 2018-05-13 19:42
now fixed

**Closed by rom1504** 2018-05-13 19:42 UTC
Labels: bug
