### ISSUE TITLE
How to add Proxy SOCKS5 Bots

### ISSUE THREAD

**Issue by Msgumor** [PrismarineJS/mineflayer#1770] opened 2021-03-17 18:12 UTC
mineflayer: 3.2.0
server: Spigot
node: 14.16.0

give a script for a SOCKS5 proxy, those scripts that are already on the internet do not work for me 

please

**Comment by BlueBurgersTDD** [comment] 2021-03-17 18:30
In the options object for `mineflayer.createBot(options)`, remove your `host` option from the options object, have the following variables declared `PROXY_IP, PROXY_PORT, PROXY_USERNAME, PROXY_PASSWORD, MC_SERVER_IP, MC_SERVER_PORT` and add this to your options object:
```js
connect: (client) => {
    socks.createConnection({
      proxy: {
        host: PROXY_IP,
        port: PROXY_PORT,
        type: 5,
        userId: PROXY_USERNAME,
        password: PROXY_PASSWORD
      },
      command: 'connect',
      destination: {
        host: MC_SERVER_IP,
        port: MC_SERVER_PORT
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }
      client.setSocket(info.socket)
      client.emit('connect')
    })
  }
  ```

**Comment by Msgumor** [comment] 2021-03-17 18:32
error

**Comment by Msgumor** [comment] 2021-03-17 18:32
server mode - offline

**Comment by Msgumor** [comment] 2021-03-17 18:37
complete proxy login script?

**Comment by Msgumor** [comment] 2021-03-17 18:41
C:\Users\User\Desktop\BotTest>node index.js
C:\Users\User\Desktop\BotTest\index.js:6
        host: proxy_ip,
                     ^^^^

SyntaxError: Unexpected number
←[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

C:\Users\User\Desktop\BotTest>pause
Для продолжения нажмите любую клавишу . . .

**Comment by u9g** [comment] 2021-03-18 00:24
post your full code without passwords

**Comment by Msgumor** [comment] 2021-03-18 11:45
I have a proxy without a password and login

**Comment by BlueBurgersTDD** [comment] 2021-03-18 11:55
Then post the code

**Comment by Msgumor** [comment] 2021-03-18 16:37
connect: (client) => {
    socks.createConnection({
      proxy: {
        host: proxy_ip,
        port: 1080,
        type: 5,
      },
      command: 'connect',
      destination: {
        host: 127.0.0.1,
        port: 55602
      }
    }, (err, info) => {
      if (err) {
        console.log(err)
        return
      }
      client.setSocket(info.socket)
      client.emit('connect')
    })
  }

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  username: 'Bot_23rf4', // электронная почта и пароль требуются только для лицензии
  version: '1.12.2'                 // false соответствует автоматическому определению версии (это значение по умолчанию), укажите, например, "1.8.8", если вам нужна конкретная версия.
})

**Comment by rom1504** [comment] 2021-03-20 22:39
duplicate of https://github.com/PrismarineJS/mineflayer/issues/438

**Closed by rom1504** 2021-03-20 22:39 UTC
Labels: question
