### ISSUE TITLE
the bot floats above snow layers

### ISSUE THREAD

**Issue by ooodlllars** [PrismarineJS/mineflayer#875] opened 2019-10-28 00:39 UTC
## Versions
 - mineflayer: 2.9.6
 - server: spigot 1.8.8
 - node: 10.15.3

## Detailed description of a problem
A clear and concise description of what the problem is.

## Current code
```js
const mf = require("mineflayer");
const mfnav = require("mineflayer-navigate")(mf);
const mfbf = require("mineflayer-blockfinder")(mf);

const V3 = require("vec3");
const Vec3 = V3.Vec3;
var url = "[redacted]";
url = url.split(":");
var bot = mf.createBot({
  host: url[0],
  port: Number(url[1]),
  username: "[redacted]"
});

mfnav(bot);
mfbf(bot);
var spam,
    a;
bot.on("chat", (username, message) => {
  var args = message.split(" ");
  args.shift();
  if (username === "[redacted]") {
    if (message.toLowerCase().startsWith("-eval")) {
      try {
        bot.chat(eval(args.join(" ")).toString());
      } catch (err) {
        bot.chat(err.toString());
      }
    } else if (message.toLowerCase().startsWith("-nav")) {
      bot.navigate.stop();
      bot.navigate.to(bot.players[username].entity.position.offset(1, 0, 0));
      bot.chat("navigating to you");
    } else if (message.toLowerCase().startsWith("-spam")) {
      spam = setInterval(function() {
        try {
          bot.chat(bot.players["[redacted]"].entity.position.toString());
        } catch (err) {
          bot.chat("can't get position");
        }
      }, 1000);
    } else if (message.toLowerCase().startsWith("-stopspam")) {
      clearInterval(spam);
    } else if (message.toLowerCase().startsWith("-dev")) {
      Object.keys(bot.entities).forEach(entity => {
        if (bot.entities[entity].name === "Pig") {
          bot.mount(bot.entities[entity]);
          a = bot.entities[entity];
        }
      });
    }
  }
});
bot.on("kicked", (reason, good) => {
  console.log(reason);
  setTimeout(function(){require("child_process").exec("refresh");}, 5000);
});
bot.on("login", () => {
  setTimeout(function(){
    setInterval(function() {
      try {
        bot.lookAt(bot.players["[redacted]"].entity.position.offset(0, 1.5, 0));
      } catch (err) {
        void(0);
      }
    }, 100);
  }, 10000);
});
```

## Expected behavior
The bot should go on the snow, not float

**Comment by wvffle** [comment] 2019-10-28 07:28
Duplicate of #692

**Closed by wvffle** 2019-10-28 07:28 UTC
Labels: possible bug
