### ISSUE TITLE
Bot crash dropping Enchanted Items.

### ISSUE THREAD

**Issue by BorgesTar** [PrismarineJS/mineflayer#2895] opened 2023-01-17 03:08 UTC
## Versions
 - mineflayer: 4.6.0
 - server: vanilla/spigot/paper 1.8.9

## Your current code
```   
else if (message.content.startsWith('!drop')) {
    let split = message.content.split(' ')
    if (split[1] == bot.username || split[1] == 'all') {
      channel.send(Dropando: ${username})
      for (item of bot.inventory.items()) {
          await bot.tossStack(item);
          await utils.sleep(2500);
      }
      return;
    }
  }

```

## Detailed description of a problem

Bot crash dropping enchanted items.
Normal Items no enchantments work and drop normally.
Is this a bug? or an error in my code?
I tried to use code #1241 but it didn't work

**Comment by Zakarya1000** [comment] 2023-01-17 16:28
Can you upload the error to a pastebin? I'm curious about this.

**Comment by BorgesTar** [comment] 2023-01-17 18:54
There are no errors, the console just closes. I try to drop normal items it drops without fail

I do not know what happens

**Comment by MightyPiggie** [comment] 2023-01-25 17:50
I tested it and it just drops enchanted items on 1.8.9 fine for me without crashing.

This is the code I used. Probably not the best, but it does the job.

```
function sleep(ms) {
    return new Promise((resolve) => {
        setTimeout(resolve, ms);
    });
}

async function drop_items(message){
    if (message.startsWith('!drop')) {
        let split = message.split(' ')
        if (split[1] == bot.username || split[1] == 'all') {
          for (item of bot.inventory.items()) {
              await bot.tossStack(item);
              await sleep(2500);
          }
          return;
        }
      }
  }
bot.on('chat', (username, message) => {
    if (username === bot.username) return
    else drop_items(message);
})
```

In the meantime this issue can be closed as it works as intended? @extremeheat

**Comment by extremeheat** [comment] 2023-02-10 05:04
Try the code from MightyPiggie above, you can re-open if it's still an issue

**Closed by extremeheat** 2023-02-10 05:04 UTC
Labels: possible bug, Stage1
