### ISSUE TITLE
Bot can't craft pickaxes/tools

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#1576] opened 2021-01-08 04:31 UTC
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 
## Versions
 - mineflayer: 2.40.1
 - server: vanilla 1.16.4
 - node: v15.5.0

## Detailed description of a problem
Can not craft tools (I suppose multi material recipes), but can craft furnaces.

The bot says for example
: 
error making stone_pickaxe

but no error in the console

## What did you try yet?

The only thing that helps is by manually breaking the block. I did not try to change the source code of the modules.

Maybe there is a packet that can get the block state/type of a single block?

## Your current code
```js

//the example code


```

## Expected behavior
It should craft the pickaxe as normal

**Comment by SinanAkkoyun** [comment] 2021-01-08 04:32
Added:

Bot thinks it does not have the items used for the failed recipe after it failed


And thus drop item does not work etc

**Comment by AndrewLemons** [comment] 2021-01-10 16:43
I have run into the same issue. It would be great if there was at least a temporary work around. Pretty annoying.

I have `bot.craft()` logging the error it runs into (through `.catch(err)`). It states the following:
```
Error: Server rejected transaction.
    at clickWindow (***/node_modules/mineflayer/lib/plugins/inventory.js:540:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async putAway (***/node_modules/mineflayer/lib/plugins/inventory.js:545:5)
    at async grabResult (***/node_modules/mineflayer/lib/plugins/craft.js:121:9)
    at async putMaterialsAway (***/node_modules/mineflayer/lib/plugins/craft.js:112:9)
    at async nextShapeClick (***/node_modules/mineflayer/lib/plugins/craft.js:65:11)
    at async clickShape (***/node_modules/mineflayer/lib/plugins/craft.js:85:9)
    at async nextShapeClick (***/node_modules/mineflayer/lib/plugins/craft.js:63:11)
    at async clickShape (***/node_modules/mineflayer/lib/plugins/craft.js:85:9)
```
Hope that helps.

**Comment by AndrewLemons** [comment] 2021-01-10 20:59
Ok, did some "debug" modifications to `./lib/plugins/craft.js`. Interesting results...

I added a `console.log()` for every step of the `grabResult` function.
``` javascript
async function grabResult () {
  console.log("assert.strictEqual")
  assert.strictEqual(window.selectedItem, null)
  // put the recipe result in the output
  console.log("window.updateSlot")
  const item = new Item(recipe.result.id, recipe.result.count, recipe.result.metadata)
  window.updateSlot(0, item)
  console.log("bot.putAway")
  // move the result to inventory
  await bot.putAway(0)
  console.log("updateOutShape")
  await updateOutShape()
}
```
Pretty self explanatory. Here is the kicker, the console logs:
```
assert.strictEqual
window.updateSlot
bot.putAway
```
Woah! `updateOutShape` is missing. So, my guess is that the error occurs around `await bot.putAway(0)`. Some sort of error occurs that the server (or the bot?) does not like. `bot.putAway` is defined in `./lib/plugins/inventory.js`, so I decided to do the same debugging procedures.
``` javascript
async function putAway (slot) {
  console.log("clickWindow")
  await clickWindow(slot, 0, 0)
  console.log("set window")
  const window = bot.currentWindow || bot.inventory
  console.log("set start")
  const start = window.inventoryStart
  console.log("set end")
  const end = window.inventoryEnd
  console.log("putSelectedItemRange")
  await putSelectedItemRange(start, end, window, null)
}
```
And the console logs
```
clickWindow
```
That narrows the problem down to `clickWindow`. I felt like I was getting close, so I did the debug yet again! The `clickWindow` function is pretty big, so I'll just give the problematic code...
``` javascript
const [success] = await response
if (!success) {
  throw new Error('Server rejected transaction.')
}
```
Ah! That's the error I got earlier! `request`, which seems to be missing, is set in the code like so...
``` javascript
const response = once(bot, `confirmTransaction${actionId}`)
```
`await response`, according to `success`, is simply `false`. I have no clue what the problem could be. Either way:

**The problem arises with `clickWindow` in `./lib/plugins/inventory.js`**

**Comment by Karang** [comment] 2021-01-10 21:10
Did you verify that the recipe is correct ?

**Comment by rom1504** [comment] 2021-01-10 21:13
This is caused by https://github.com/PrismarineJS/minecraft-data/issues/231
Several people have solved it on their side without making a PR with the result.
Will any of you be the one finally solving this for good ?

**Comment by AndrewLemons** [comment] 2021-01-10 23:53
Man, I feel so stupid after doing all that work. Anyways...

I would love to fix the problem but I wouldn't even know where to start. As a personal, temporary, solution, I found that the following works.
``` javascript
recipe.inShape.reverse();
```
Thanks for the help, this was driving me insane.

**Comment by rom1504** [comment] 2021-01-11 00:18
now fixed (by https://github.com/PrismarineJS/minecraft-data/pull/349) ; just update your packages

**Closed by rom1504** 2021-01-11 00:18 UTC
Labels: possible bug

**Comment by rom1504** [comment] 2021-01-11 00:23
https://github.com/PrismarineJS/minecraft-data/issues/351 and https://github.com/PrismarineJS/minecraft-data/issues/350 can be good follow ups
