### ISSUE TITLE
Transaction Packet Response

### ISSUE THREAD

**Issue by Greenlio** [PrismarineJS/mineflayer#2189] opened 2021-09-10 05:08 UTC
## Is your feature request related to a problem? Please describe.
Well, when trying to use on some servers, their anticheat detects the bot and kicks for 'not responding to transaction packets'. It's frustrating. I've talked to these server owners too, one of the anticheats that I know does is Vulcan, and it simply kicks after 30~ seconds for "Not Responding to Transaction Packets (numbers)ms.". It's nothing they can fix, so I was wondering if you guys could.

## Describe the solution you'd like
I would like a fix to be made, *if possible*, if not, that is perfectly fine, and I understand it's a limitation, as this is a feature request.

## Describe alternatives you've considered
Oh, at first I thought it was some issue keepAlive, but that's already been considered and fixed. I've tried moving around, sending chat, etc. So, it's not something depending on movement of the player. Yeah. That's about it.

## Additional context
N/A

**Comment by Greenlio** [comment] 2021-09-10 17:29
heck, it fixed itself i dont know how.

**Comment by Greenlio** [comment] 2021-09-10 17:30
nvm, it only fixes with using minecraft-protocol instead of mineflayer. weird.

**Comment by GenixZero** [comment] 2021-09-20 09:54
Hey, I had the same issue with vulcan and I spent some time looking into the code. This behaves exactly like the 1.8.9 client does, I'm sure it would be the same throughout all versions until 1.17 because they removed the packet i think.

```
bot._client.on("transaction", (packet) => {
     if (!packet.accepted && (packet.windowId == 0 || packet.windowId == bot.currentWindow.windowId)) {
        bot._client.write('transaction', {windowId: packet.windowId, action: packet.action, accepted: true});
    }
});
```

**Comment by Greenlio** [comment] 2021-09-21 20:54
Interesting, thanks. I'll try when I get home.

**Comment by U5B** [comment] 2021-09-22 01:19
```js
bot._client.on('ping', (data, packetMeta) => {
  console.log(data)
  bot._client.write('pong', {
    id: data.id
  })
})
```
This is for 1.17.1 Vulcan servers. They use this instead in 1.17.
Don't know where this would go to mimic the vanilla client.

**Comment by Greenlio** [comment] 2021-12-04 06:34
i see no recognizable progress on this issue and has been inactive for 2+ months. closing ticket, have a great night everyone.

**Comment by extremeheat** [comment] 2021-12-04 12:31
If an issue is still valid there is no need to close it. There’s information here missing that makes it harder for a fix:

* what version are you running on?
* Where to download the anti cheat or where to join to test it?
* Steps to reproduce

Can anyone else confirm it’s still a problem and the versions? @U5B @Greenlio

**Comment by U5B** [comment] 2021-12-05 06:49
> If an issue is still valid there is no need to close it. There’s information here missing that makes it harder for a fix:
> 
> * what version are you running on?
> * Where to download the anti cheat or where to join to test it?
> * Steps to reproduce
> 
Version: any
Server: Hypixel
Join Hypixel and see if the bot gets sent to limbo after a minute.

PR 2217 fixes this issue, however it has not been merged and has not seen activity recently

**Closed** 2021-12-25 09:22 UTC
Labels: new feature, Stage1

**Comment by AntonqMC** [comment] 2022-10-02 07:26
i got same problem but its server side problem:
if server antycheat is vulcan and its wrong cofigured when somebody join on cracked they got message they cant join because this nick is on server, but then vulcan trigger on this ip and this ip isnt on server so it cant respond on packet
