### ISSUE TITLE
Add TheAltening support

### ISSUE THREAD

**Issue by AdolfRoxler** [PrismarineJS/mineflayer#2717] opened 2022-07-28 01:58 UTC
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I don't have 200 mc accounts lying around

## Describe the solution you'd like

I want support for authing via TheAltening

## Describe alternatives you've considered

Sorry. I won't kill my cpu to load 8 meteor client instances.

**Comment by extremeheat** [comment] 2022-07-28 02:23
Dupe of #790

**Closed by extremeheat** 2022-07-28 02:23 UTC
Labels: new feature, Stage1

**Comment by extremeheat** [comment] 2022-07-28 02:26
Adding official features like this (likely breaks TOS) could jeopardize the legitimacy of the project, and lead to bad attention from Mojang. Likely left to external plugin as rom wrote in the linked issue.
