### ISSUE TITLE
Needs better disconnect handling...

### ISSUE THREAD

**Issue by Darker** [PrismarineJS/mineflayer#309] opened 2015-07-12 08:49 UTC
At this point, if the bot is disconnected it either exists with uncaught error:

```
  events.js:85
        throw er; // Unhandled 'error' event
              ^
  Error: connect ECONNREFUSED
      at exports._errnoException (util.js:746:11)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

or it just stops dispatching events and doesn't even notice it's out of the game. Obviously what I want from a bot is to be as stable as possible, so I don't have to babysit it every few minutes. So, in general, I think there's a need for better handling of disconnects.

**Comment by roblabla** [comment] 2015-07-12 13:42
This might be a problem coming from node-minecraft-protocol, which does has fairly poor error handling.

**Comment by rom1504** [comment] 2015-07-21 05:09
Yeah this probably needs to be fixed in node-minecraft-protocol (is there an issue open for this ?) but in the end that's also a mineflayer issue.

**Comment by rom1504** [comment] 2020-08-30 17:38
duplicate of https://github.com/PrismarineJS/mineflayer/issues/975

**Closed by rom1504** 2020-08-30 17:38 UTC
Labels: reliability
