### ISSUE TITLE
Add Beddrock Edition Support

### ISSUE THREAD

**Issue by LeontKing2** [PrismarineJS/mineflayer#1967] opened 2021-06-03 06:53 UTC
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Add Bedrock Edition Support

## Describe alternatives you've considered
Or add Geyser Mc from bedrock support

**Comment by Hazuki-san** [comment] 2021-06-03 07:14
duplicate of #842

**Comment by TheBlueBurger** [comment] 2021-06-03 07:41
Just use https://github.com/PrismarineJS/bedrock-protocol

**Comment by LeontKing2** [comment] 2021-06-04 06:45
> Just use https://github.com/PrismarineJS/bedrock-protocol

how do i use it @TheBlueBurger  idk how to use it but all i need is to make a bot join the server and rotate random directions
and talk i chat manually

**Comment by TheBlueBurger** [comment] 2021-06-04 07:15
Read the docs

**Comment by LeontKing2** [comment] 2021-06-04 09:15
i read the docs but i still dont understand js lol

**Comment by TheBlueBurger** [comment] 2021-06-04 09:20
1. Learn JS
2. Join the discord

**Comment by LeontKing2** [comment] 2021-06-06 05:03
oof

**Comment by XfedeX** [comment] 2021-06-16 20:41
> 
> 
>     1. Learn JS
> 
>     2. Join the discord

3. Play Minecraft Java Edition and not Bedrock Edition.

**Comment by rom1504** [comment] 2021-06-16 20:55
duplicate

**Closed by rom1504** 2021-06-16 20:55 UTC
Labels: Stage1, new feature
