### ISSUE TITLE
Click on a entity

### ISSUE THREAD

**Issue by Systemwartung** [PrismarineJS/mineflayer#926] opened 2020-03-25 11:42 UTC
Hey,

I have a question I have made a BOT. The function is that he clicks on an NPC but he clicks on a hologram how can I define which entity I mean?

Please give me a reason

**Comment by wvffle** [comment] 2020-03-25 12:29
Duplicate of #925
Duplicate of #826 

> You can get it from an event or from `bot.entities` or `bot.players[username].entity`.

**Comment by Systemwartung** [comment] 2020-03-25 12:44
yes but how do I define which entity I mean you can give me an example

**Closed** 2020-03-25 18:32 UTC
Labels: question
