### ISSUE TITLE
1.19.4 Support

### ISSUE THREAD

**Issue by SimplySnox** [PrismarineJS/mineflayer#3044] opened 2023-05-08 23:31 UTC
Any updates as to when support for 1.19.4 will be added? I would love to see this added sometime, thanks! :)

**Comment by LiamTheNinja5** [comment] 2023-05-09 00:12
https://github.com/PrismarineJS/node-minecraft-protocol/issues/1097

**Comment by andriycraft** [comment] 2023-05-11 10:16
dupe of #3005

**Closed** 2023-05-13 16:06 UTC
Labels: new feature, Stage1
