### ISSUE TITLE
Can not shift click inventory slots

### ISSUE THREAD

**Issue by RMJTromp** [PrismarineJS/mineflayer#1937] opened 2021-05-26 20:51 UTC
https://github.com/PrismarineJS/mineflayer/blob/a0befeb042fe3851ac35887da116c2910f505791/lib/plugins/inventory.js#L382
Shift-clicking inventory not supported because assertion only allows `mode` to be 0. Whereas the Minecraft protocol wiki website states that there are 6 possible clicking modes. <https://wiki.vg/Protocol#Click_Window>

**Comment by u9g** [comment] 2021-05-26 21:05
This is because the our inventory management package prismarine-windows only supports that type of click. If you would like more modes, you are free to contribute to add that click type to prismarine-windows so that you could use that click on mineflayer.

**Comment by KaffinPX** [comment] 2021-05-27 21:08
^^^

**Comment by rom1504** [comment] 2021-05-30 15:22
duplicate of #271

**Closed by rom1504** 2021-05-30 15:22 UTC
