### ISSUE TITLE
Command kick issue (RE-OPENED)

### ISSUE THREAD

**Issue by PitPot1** [PrismarineJS/mineflayer#2954] opened 2023-02-21 17:44 UTC
This issue was reopened as the solution given in the previous one did not fix it (this is a new issue because i cant re open the old one myselff)
Original issue: https://github.com/PrismarineJS/mineflayer/issues/2953

## Versions
 - mineflayer: 4.8.1
 - server: velocity
 - node: #.#.#

## Detailed description of a problem
NOTE: The server is Minehut.com
Bot gets kicked for "Chat message validation failure" or "Received chat packet with missing or invalid signature." when sending a message that gets edited by the server (using the /ad command). Sending normal chat messages works fine but as soon as you run the /ad command you get kicked and all your chat messages after that get you kicked aswell.

## What did you try yet?

My bot version is on 1.19.3 (the required version to chat on the server).
I have the latest Mineflayer version.

## Tried:
npm update --depth 9999

## Expected behavior
The message goes thru and the bot dosen't get kicked.

**Comment by extremeheat** [comment] 2023-02-21 17:46
cc @frej4189

**Comment by frej4189** [comment] 2023-02-21 18:35
> cc @frej4189 

This is fixed with your nmp PR. Command signing is not implemented currently

**Comment by extremeheat** [comment] 2023-02-21 21:21
Dupe of #2874

**Closed by extremeheat** 2023-02-21 21:21 UTC
Labels: possible bug, Stage1
