### ISSUE TITLE
Using anvils

### ISSUE THREAD

**Issue by RegenixMC** [PrismarineJS/mineflayer#1665] opened 2021-02-12 18:12 UTC
Is there a way to put enchantment books on gear using a Anvil with mineflayer.

**Comment by u9g** [comment] 2021-02-12 18:13
anvils arent implemented in mineflayer

**Comment by RegenixMC** [comment] 2021-02-12 18:14
Can you add it maybe? That would be very useful.

**Comment by u9g** [comment] 2021-02-12 18:15
https://github.com/PrismarineJS/mineflayer/issues/237 follow the progress here

**Comment by u9g** [comment] 2021-02-21 01:38
can be closed, duplicate of #237

**Closed** 2021-03-01 01:31 UTC
Labels: question
