### ISSUE TITLE
Mineflayer don't accept shift-click mode in bot.clickWindow

### ISSUE THREAD

**Issue by Afton720** [PrismarineJS/mineflayer#2589] opened 2022-04-17 14:38 UTC
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.2.0
 - server: Paper git-Paper-794 (MC: 1.16.5)
 - node: 16.14.2

## Detailed description of a problem
When I try to shift-click on a slot I get an AssertionError
I checked the mineflyer code and saw this (line 489):
```js
assert.strictEqual(mode, 0)
```
This means that the bot.clickWindow function does not accept a mode argument that is different from 0. Although according to https://wiki.vg/Protocol#Click_Window the mode can be from 0 to 6

## What did you try yet?

Did you try any method from the API? Yes, bot.clickWindow

## Your current code
```js
async function moveToInv(item) { 
    await bot.clickWindow(item.slot, 0, 1)
}
```

## Expected behavior
Bot shift-clicks on chest slot, and item stack moves to bot inventory

**Comment by IceTank** [comment] 2022-04-17 18:07
This is because mineflayer's inventory code cannot handle shift clicking. If you would send this packet the inventory off the bot would desync. So not a bug just not implemented.

**Comment by u9g** [comment] 2022-04-19 17:44
duplicate of https://github.com/PrismarineJS/mineflayer/issues/271

**Closed** 2022-04-19 17:44 UTC
Labels: possible bug, Stage1
