### ISSUE TITLE
Installation doesnt work.

### ISSUE THREAD

**Issue by Kavatch** [PrismarineJS/mineflayer#474] opened 2017-01-31 14:22 UTC
Ok.
I have been trying to install the bot now for over 5 hours and it still dosn't work.
I have tryed it multiple times now  but it doesn't seem to work.
Here is the log of the npm test maby it can help.
http://pastebin.com/raw/2bLTtDMn

Also I tryed to use this: `var mineflayer = require('mineflayer');`
but it also throws this error in chrome: `Uncaught ReferenceError: require is not defined`

Soooo can someone help me to get it installed proerly?
And not only "npm install mineflayer" because this doesn't work...

**Comment by rom1504** [comment] 2017-01-31 15:01
What version of node are you using ?
What did you try do to ?
What error do you get when running npm install mineflayer ?

**Comment by Kavatch** [comment] 2017-01-31 15:12
What version of node are you using ? -> v7.4.0
What did you try do to ? -> Install the bot and then using it for pathfinding / other tasks
What error do you get when running npm install mineflayer ? -> This is everything it shows in the log: http://pastebin.com/raw/VxaTXscx

**Comment by rom1504** [comment] 2017-01-31 15:13
Ok so npm install works.
Again "What did you try do to ?"
I mean, not your objective, what did you run exactly, what code, what directory, etc

**Comment by Kavatch** [comment] 2017-01-31 15:21
This is my script: http://pastebin.com/raw/61wC809y (Its from here: https://github.com/andrewrk/mineflayer-navigate/)

**Comment by rom1504** [comment] 2017-01-31 15:26
ok the problem is `<script>`
This will not work in the browser.
You need to run this with `node`

**Comment by Kavatch** [comment] 2017-01-31 15:33
Ok thanks! That already worked better but now im getting this error when I start it.

> node run.js
module.js:472
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/Bot/run.js:3:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by rom1504** [comment] 2017-01-31 15:37
replace `../` by `mineflayer-navigate`

**Comment by rom1504** [comment] 2017-01-31 15:41
oh and you need to use https://github.com/andrewrk/mineflayer-navigate/pull/28 if you're using mineflayer 2.0.0

**Comment by Kavatch** [comment] 2017-01-31 15:45
So like this? http://pastebin.com/raw/g2BGZmGn
Because this will still give me this error: 
module.js:472
    throw err;
    ^

Error: Cannot find module 'mineflayer-navigate'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/Bot/run.js:3:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by rom1504** [comment] 2017-01-31 15:48
ok run `npm install rom1504/mineflayer-navigate#update_vec3`

**Comment by Kavatch** [comment] 2017-01-31 15:53
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "rom1504/mineflayer-navigate#update_vec3"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "mineflayer-navigate" under a package
npm ERR! also called "mineflayer-navigate". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/Bot/npm-debug.log

npm-debug.log: http://pastebin.com/raw/BsRwf38u

And sorry if this is a bit annoying :s But I realy dont know it better :l

**Comment by rom1504** [comment] 2017-01-31 15:54
well.... where did you run this ?
Run it in your "Bot" dir

**Comment by Kavatch** [comment] 2017-01-31 15:57
I have run it in the Bot dir: ***@*********:/var/www/html/Bot# npm install rom1504/mineflayer-navigate#update_vec3

**Comment by Kavatch** [comment] 2017-01-31 15:58
I changed nothing in it its still this:
{
  "name": "mineflayer-navigate",
  "version": "0.0.9",
  "description": "mineflayer plugin which adds 3d pathfinding",
  "main": "index.js",
  "devDependencies": {
    "mineflayer": "0.0.18"
  },
  "repository": "git://github.com/superjoe30/mineflayer-navigator.git",
  "keywords": [
    "mineflayer",
    "minecraft",
    "bot",
    "path",
    "finding",
    "navigation"
  ],
  "author": "Andrew Kelley",
  "license": "BSD",
  "dependencies": {
    "a-star": "~0.1.0"
  }
}

**Comment by rom1504** [comment] 2017-01-31 15:59
Ok that shouldn't be in the Bot dir.
Remove that file and run npm init.

**Comment by roblabla** [comment] 2017-01-31 16:01
@Kavatch rm -rf everything. Do this : 

```
mkdir my_minecraft_bot
cd my_minecraft_bot
npm init # It will ask you a few questions, answer them. the defaults should be fine
npm i --save mineflayer
npm i --save rom1504/mineflayer-navigate#update_vec3
curl http://pastebin.com/raw/NayLXamq > index.js
node index.js
```

**Comment by Kavatch** [comment] 2017-01-31 16:09
@roblabla Firstly thanks! It hasnt thrown any error but sadly the bot isnt connecting :s

**Comment by rom1504** [comment] 2017-01-31 16:11
@Kavatch put the host adress and port, and your username/password in the createBot function instead of the example one in your script ;)

**Comment by Kavatch** [comment] 2017-01-31 16:12
@rom1504 I have changed them ^^

**Comment by roblabla** [comment] 2017-01-31 16:12
@Kavatch is your server in online or offline mode ? And what minecraft version is it ?

**Comment by Kavatch** [comment] 2017-01-31 16:13
- Online mode.
- 1.8.x

**Comment by rom1504** [comment] 2017-01-31 16:13
Ah yes you need to specify the version in createBot if it's not the default (`1.11.2`)

**Comment by rom1504** [comment] 2017-01-31 16:14
ok so put `version:"1.8.8"` in createBot

**Comment by Kavatch** [comment] 2017-01-31 16:17
@rom1504 Jep it was the `version:"1.8.8"`. Now it works. Thanks a lot!

**Comment by roblabla** [comment] 2017-01-31 16:18
Cool :D Closing now.

**Closed by roblabla** 2017-01-31 16:18 UTC
