### ISSUE TITLE
1.16.3 Connection Problem

### ISSUE THREAD

**Issue by Nisutec** [PrismarineJS/mineflayer#1310] opened 2020-09-11 17:49 UTC
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.28.1
 - server: paper 1.16.3
 - node: v13.3.0

## Detailed description of a problem
When i try to connect to a 1.16.3 Server i recieve the following error.

```
Error: Cannot read property 'minecraftVersion' of undefined
    at C:\Users\Niclas\IdeaProjects\mc_client\node_modules\minecraft-protocol\src\client\autoVersion.js:34:42
    at Client.<anonymous> (C:\Users\Niclas\IdeaProjects\mc_client\node_modules\minecraft-protocol\src\ping.js:32:7)
    at Object.onceWrapper (events.js:309:26)
    at Client.emit (events.js:219:5)
    at FullPacketParser.<anonymous> (C:\Users\Niclas\IdeaProjects\mc_client\node_modules\minecraft-protocol\src\client.js:89:12)
    at FullPacketParser.emit (events.js:219:5)
    at addChunk (C:\Users\Niclas\IdeaProjects\mc_client\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Niclas\IdeaProjects\mc_client\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\Niclas\IdeaProjects\mc_client\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (C:\Users\Niclas\IdeaProjects\mc_client\node_modules\readable-stream\lib\_stream_transform.js:139:32)
```

## What did you try yet?

-

## Your current code
```js

const mineflayer = require('mineflayer')

const options = {
    host: 'localhost',
    port: 25565,
    username: `<username>`,
    password: `<password>`
}

const bot = mineflayer.createBot(options)


```

## Expected behavior
The Bot connect to the Server

## Additional context
-

**Comment by rom1504** [comment] 2020-09-11 17:51
Yes it's not supported yet

**Comment by Karang** [comment] 2020-09-16 20:52
duplicate of https://github.com/PrismarineJS/mineflayer/issues/1316

**Closed by Karang** 2020-09-16 20:52 UTC
Labels: possible bug
