### ISSUE TITLE
Bug with imports in TypeScript (ECMAscript)

### ISSUE THREAD

**Issue by zxxxxo** [PrismarineJS/mineflayer#3032] opened 2023-04-23 23:33 UTC
- [yes] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: [newest version]
 - server: vanilla/spigot/paper hypixel, not sure but spigot most likely
 - node: [newest version]

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

> ../node_modules/mineflayer/index.d.ts:11:10 - error TS2305: Module '"prismarine-registry"' has no exported member 'Registry'.
> 
> 11 import { Registry } from 'prismarine-registry'
>             ~~~~~~~~
> 
> ../node_modules/mineflayer/index.d.ts:11:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.
> 
> 11 import { Registry } from 'prismarine-registry'
>                             ~~~~~~~~~~~~~~~~~~~~~

                            

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

not well versed in typescript, not sure how to try

## Your current code
```js

simple mineflayer bot, connects to hypixel and leaves


```

## Expected behavior
connects to hypixel, no import errors

**Comment by extremeheat** [comment] 2023-04-23 23:36
Please search through all the issues before making a new one, dupe of https://github.com/PrismarineJS/mineflayer/issues/2862

**Closed by extremeheat** 2023-04-23 23:36 UTC
Labels: possible bug, Stage1

**Comment by zxxxxo** [comment] 2023-04-23 23:49
Following the suggested steps, it now returns the error

> ../node_modules/mineflayer/index.d.ts:11:9 - error TS1259: Module '"C:/Users/z/Downloads/adbot/adbot/node_modules/prismarine-registry/index"' can only be default-imported using the 'esModuleInterop' flag
> 
> 11 import  Registry  from 'prismarine-registry'
>            ~~~~~~~~
> 
>   ../node_modules/prismarine-registry/index.d.ts:14:1
>     14 export = loader
>        ~~~~~~~~~~~~~~~
>     This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
> 
> ../node_modules/prismarine-biome/index.d.ts:1:8 - error TS1259: Module '"C:/Users/z/Downloads/adbot/adbot/node_modules/prismarine-registry/index"' can only be default-imported using the 'esModuleInterop' flag
> 
> 1 import Registry from 'prismarine-registry'
>          ~~~~~~~~
> 
>   ../node_modules/prismarine-registry/index.d.ts:14:1
>     14 export = loader
>        ~~~~~~~~~~~~~~~
>     This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
> 
> ../node_modules/prismarine-block/index.d.ts:5:8 - error TS1259: Module '"C:/Users/z/Downloads/adbot/adbot/node_modules/prismarine-registry/index"' can only be default-imported using the 'esModuleInterop' flag
> 
> 5 import Registry from 'prismarine-registry';
>          ~~~~~~~~
> 
>   ../node_modules/prismarine-registry/index.d.ts:14:1
>     14 export = loader
>        ~~~~~~~~~~~~~~~
>     This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
> 

Also, the error is coming from a different package and it is also a different error, as shown here.
![207449615-3b8d1efe-4410-4295-b9ce-4562d8140719](https://user-images.githubusercontent.com/46723925/233873026-8bbb7f0b-853d-4982-935a-abcc8b4a3684.png)

before opening this issue, I did search through the issues, but  a solution was not found

Requesting for this issue to be reopened @extremeheat

**Comment by zxxxxo** [comment] 2023-04-23 23:51
I do think that the error is not in mineflayer, but in prismarine registery. Asking for confirmation

>  ../node_modules/prismarine-registry/index.d.ts:14:1
>     14 export = loader
>        ~~~~~~~~~~~~~~~
>     This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

**Comment by extremeheat** [comment] 2023-04-24 01:51
> Requesting for this issue to be reopened

the other one is still open

**Comment by zxxxxo** [comment] 2023-04-24 11:16
> > Requesting for this issue to be reopened
> 
> the other one is still open

@extremeheat do think think it's mineflayer or the other package thats bugging out

**Comment by DxxxxY** [comment] 2023-05-22 21:10
As these errors still exist, I've made an alternate package `@dxxxxy/mineflayer` (https://github.com/DxxxxY/mineflayer) which uses my three other alternate fixed packages related to the Registry export type mishap.

**Comment by u9g** [comment] 2023-05-23 00:23
> As these errors still exist, I've made an alternate package `@dxxxxy/mineflayer` (https://github.com/DxxxxY/mineflayer) which uses my three other alternate fixed packages related to the Registry export type mishap.

Would you mind pr'ing these?

**Comment by DxxxxY** [comment] 2023-05-23 02:52
> > As these errors still exist, I've made an alternate package `@dxxxxy/mineflayer` (https://github.com/DxxxxY/mineflayer) which uses my three other alternate fixed packages related to the Registry export type mishap.
> 
> 
> 
> Would you mind pr'ing these?

I was looking around before this and some of these changes are actually already implemented on the latest branches. They're simply unpublished or unused by mineflayer.

**Comment by DxxxxY** [comment] 2023-05-23 02:54
Also, I had to go back to the published versions of the packages because the fix wouldn't work on the latest commits.
