### ISSUE TITLE
better document unknown transaction confirmation

### ISSUE THREAD

**Issue by Skeec54** [PrismarineJS/mineflayer#1087] opened 2020-06-25 13:20 UTC
[X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.22.0
 - server: paper 1.15.2
 - node: 12.16.3

## Detailed description of a problem
A clear and concise description of what the problem is.

## Current code
```js
const minecraft = require('mineflayer')
const chalk = require('chalk')




function createbot() {
    
const bot = minecraft.createBot({
    host: "134.255.234.15",
    port: "2864",
    username: process.env.minecraftusername,
    password: process.env.minecraftpsw,
    version: "1.15.2"
})
bot.on('login', () => {
    console.log(chalk.greenBright('SkyblockVerify Online!'))
})
bot.on('chat', function(username, message) {
    if (username === bot.username) return;
    console.log(message)
  });
  bot.on('error', err => {

  })
}

exports.createbot = createbot
```

Console is getting spammed with "WARNING : unknown transaction confirmation for window 0, action 1430 and accepted false"
about every 10s

**Comment by rom1504** [comment] 2020-08-30 17:32
duplicate of https://github.com/PrismarineJS/mineflayer/issues/1117

**Closed by rom1504** 2020-08-30 17:32 UTC
Labels: documentation
