### ISSUE TITLE
Add `bot.reconnect()`

### ISSUE THREAD

**Issue by FeixuRuins** [PrismarineJS/mineflayer#1835] opened 2021-04-04 12:42 UTC
## Is your feature request related to a problem? Please describe.
It's a pain to reconnect the bot when it's kicked.

## Describe the solution you'd like
Some way for it to log back in.

**Comment by rom1504** [comment] 2021-04-04 12:49
You can follow the same pattern as https://github.com/PrismarineJS/mineflayer/blob/master/examples/reconnector.js

For the in-built function, duplicate of #975

**Closed by rom1504** 2021-04-04 12:49 UTC
Labels: Stage1, new feature
