### ISSUE TITLE
unexpected end of file

### ISSUE THREAD

**Issue by MrSonicMaster** [PrismarineJS/mineflayer#431] opened 2016-06-17 01:42 UTC
Whenever i connected to a server, i get this error:
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)

What should i try to do to fix this?

EDIT:
If i add a bot.on('error') i get this
Bot error { [Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR' }

**Comment by Slushpies** [comment] 2017-01-17 08:58
How was this solved?

**Comment by rom1504** [comment] 2017-01-17 21:59
reproduced on `mc.desiredcraft.net`
Not sure what is up

**Comment by rom1504** [comment] 2017-01-17 22:01
same error with nmp

**Comment by MrSonicMaster** [comment] 2017-01-20 18:14
Yeah, that's the same server I tested it on.

**Comment by mcparadip** [comment] 2017-03-02 00:52
Same error

**Comment by mcparadip** [comment] 2017-03-02 00:55
Same error, but only when i have a block of code that receives chat packets.

**Comment by mcparadip** [comment] 2017-03-02 00:57
Has this been solved?

**Comment by mcparadip** [comment] 2017-03-02 01:06
It works fine on RunKit online, maybe it's the node version.

**Comment by MrSonicMaster** [comment] 2017-06-13 04:23
Sadly, I lost the code I used before to fix the error or else I would put it here.

**Comment by mcparadip** [comment] 2017-06-13 04:48
@rom1504 said in the other issue:

> If I just ignore that chunk (return cb() instead of return cb(err)) everything else seems to work.

So yea do that.

**Comment by mcparadip** [comment] 2017-06-13 04:49
He's talking about https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/transforms/compression.js#L64

**Comment by johnpyp** [comment] 2018-01-03 18:57
This is the most pressing issue for me. I've had to maintain a fork implementing this "quick fix" and its pretty annoying, especially because it seems to cause other bugs.

**Comment by rom1504** [comment] 2018-08-03 19:15
fixed in https://github.com/PrismarineJS/node-minecraft-protocol/issues/462 + https://github.com/PrismarineJS/node-minecraft-protocol/commit/9cb5810597fed419f65d7a86e7f18c350aabab27

**Closed by rom1504** 2018-08-03 19:15 UTC
Labels: bug, non-vanilla

**Comment by lefela4** [comment] 2018-12-01 01:41
Yo @MrSonicMaster lmao

**Comment by lefela4** [comment] 2018-12-01 21:13
I just figure out the zlib issue with some packet on some servers xD.
I just look online for the sharing compressed data chunks and I figured the issue out. If this is still alive I will post it there.

**Comment by rom1504** [comment] 2018-12-02 12:54
Yes the issue is still open so we still need the fix.
Please share ;)

**Comment by lefela4** [comment] 2018-12-02 15:44
Dupe of https://github.com/PrismarineJS/mineflayer/issues/753#issuecomment-443505337
