### ISSUE TITLE
protocolsupport incompatibility

### ISSUE THREAD

**Issue by S0LDR** [PrismarineJS/mineflayer#1162] opened 2020-07-19 00:29 UTC
## Versions
 - mineflayer: 2.24.0
 - server: paper
 - node: 12.18.2

Bot cannot connect to server with protocolsupport, the plugin that lets multiple versions join.

```
PartialReadError: Deserialization error for play.toClient : Read error for undefined : Missing characters in string, found size is 40761 expected size was 3325017
    at new ExtendableError (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:245:12), <anonymous>:46:15)
    at eval (eval at compile (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1704:71)
    at eval (eval at compile (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1781:11)
    at Object.packet_declare_recipes (eval at compile (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1786:9)
    at eval (eval at compile (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1933:70)
    at packet (eval at compile (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1938:9)
    at CompiledProtodef.read (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:64:12)
    at e.message (C:\Users\Soldr\WebstormProjects\soldrbot3.0\node_modules\.pnpm\protodef@1.8.2\node_modules\protodef\src\compiler.js:99:49) {
  partialReadError: true,
  field: 'play.toClient'
}
```

## Expected behavior
Bot connects to server fine.

**Comment by rom1504** [comment] 2020-07-19 00:34
can you post an example server and version

**Comment by S0LDR** [comment] 2020-07-19 00:35
> can you post an example server and version

endcrystal.me, 1.12.2 -> 1.15.2

**Comment by rom1504** [comment] 2020-08-30 17:29
duplicate of https://github.com/PrismarineJS/node-minecraft-protocol/issues/741

**Closed by rom1504** 2020-08-30 17:29 UTC
Labels: possible bug
