### ISSUE TITLE
Chest.window is null

### ISSUE THREAD

**Issue by Draem** [PrismarineJS/mineflayer#647] opened 2018-02-19 22:39 UTC
im trying to make my bot open a chest, put items in, then close it.
when i try to deposit items using the example from chest.js, it gives me this error
`Cannot read property 'inventorySlotStart' of null`

```
chest.deposit(item.type, null, amount, (err) => {
        if (err) {
          BOT.chat(`unable to deposit ${amount} ${item.name}`)
        } else {
          BOT.chat(`deposited ${amount} ${item.name}`)
        }
      })
```

**Comment by rom1504** [comment] 2018-02-20 08:17
Just using the example ?
What version ?

**Comment by rom1504** [comment] 2018-05-01 19:47
I just checked it, it works. 
Probably because non vanilla, duplicate of https://github.com/PrismarineJS/mineflayer/issues/571

**Closed by rom1504** 2018-05-01 19:47 UTC
Labels: bug
