### ISSUE TITLE
When will minecraft 1.14.1 be supported?

### ISSUE THREAD

**Issue by KenWa51** [PrismarineJS/mineflayer#820] opened 2019-05-25 22:06 UTC
When do you plan to update to version 1.14.1?

**Comment by wvffle** [comment] 2019-05-25 23:11
https://github.com/PrismarineJS/prismarine-chunk/issues/57 is a serious problem right now. If we solve it we can update to 1.13 and 1.14. You can work on it if you want. Currently noone is working on it as far as I know.

**Comment by rom1504** [comment] 2019-06-11 20:09
duplicate of https://github.com/PrismarineJS/mineflayer/issues/744

**Closed by rom1504** 2019-06-11 20:09 UTC
Labels: question
