### ISSUE TITLE
Unsupported brand channel name at getBrandCustomChannelName when connecting to server

### ISSUE THREAD

**Issue by VaibhavVerma21** [PrismarineJS/mineflayer#2543] opened 2022-03-24 18:09 UTC
This is my code 
`const bot = mineflayer.createBot({
  host: process.env['ip'],
  username: process.env['email'], 
  password: process.env['password'],
	auth: 'microsoft',
})`
and it is just not able to login to minecraft. why?
If you need additional info comment down.

**Comment by amoraschi** [comment] 2022-03-24 18:19
What's your error, if there's no error, try adding an error listener

**Comment by VaibhavVerma21** [comment] 2022-03-24 19:07
> What's your error, if there's no error, try adding an error listener

`Error: Unsupported brand channel name
    at getBrandCustomChannelName (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:22:11)
    at inject (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:54:24)
    at /home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:639:28)
    at EventEmitter.emit (node:events:520:28)
    at Client.next (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/loader.js:124:9)
    at Object.onceWrapper (node:events:639:28)
Error: Unsupported brand channel name
    at getBrandCustomChannelName (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:22:11)
    at inject (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:54:24)
    at /home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:639:28)
    at EventEmitter.emit (node:events:520:28)
    at Client.next (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/loader.js:124:9)
    at Object.onceWrapper (node:events:639:28)
Sign in failed, try removing the password field

/home/runner/Minecraft-bot/node_modules/@xboxreplay/errors/dist/index.js:25
    unauthorized: (message = 'Unauthorized', reason = 'UNAUTHORIZED') => new XboxReplayError(message, {
                                                                         ^

XboxReplayError: Invalid credentials.
    at Object.unauthorized (/home/runner/Minecraft-bot/node_modules/@xboxreplay/errors/dist/index.js:25:74)
    at /home/runner/Minecraft-bot/node_modules/@xboxreplay/xboxlive-auth/dist/core/live/index.js:71:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async XboxTokenManager.doReplayAuth (/home/runner/Minecraft-bot/node_modules/prismarine-auth/src/TokenManagers/XboxTokenManager.js:133:31)
    at async MicrosoftAuthFlow.getXboxToken (/home/runner/Minecraft-bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:117:20)
    at async retry.xbl.forceRefresh (/home/runner/Minecraft-bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:157:22)
    at async retry (/home/runner/Minecraft-bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:24:14)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (/home/runner/Minecraft-bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:156:7)
    at async Object.authenticate (/home/runner/Minecraft-bot/node_modules/minecraft-protocol/src/client/microsoftAuth.js:17:44) {
  __XboxReplay__: true,
  details: { statusCode: 401, reason: 'UNAUTHORIZED' }
}`
I hope i am not revealing something bad from this for my account security

**Comment by VaibhavVerma21** [comment] 2022-03-24 19:27
> remove the password field from your createbot and try again

After commenting the password line here is the error, and take this in mind it got spammed to me with no interval

`
[msa] First time signing in. Please authenticate now:
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code 43BB7ZUJ to authenticate.
Error: Unsupported brand channel name
    at getBrandCustomChannelName (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:22:11)
    at inject (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:54:24)
    at /home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:639:28)
    at EventEmitter.emit (node:events:520:28)
    at Client.next (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/loader.js:124:9)
    at Object.onceWrapper (node:events:639:28)
Error: Unsupported brand channel name
    at getBrandCustomChannelName (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:22:11)
    at inject (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:54:24)
    at /home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:639:28)
    at EventEmitter.emit (node:events:520:28)
    at Client.next (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/loader.js:124:9)
    at Object.onceWrapper (node:events:639:28)
`

**Comment by u9g** [comment] 2022-03-24 19:49
Yes, so do it once.

**Comment by VaibhavVerma21** [comment] 2022-03-24 22:56
> Yes, so do it once.

Nothing happens. When I restart it comes again

**Comment by VaibhavVerma21** [comment] 2022-03-24 23:06
> Yes, so do it once.

Ok nvm, this time it just signed in successfuly and program stopped. and when i restart it doenst ask for sign in again but program doesnt run either

`
Error: Unsupported brand channel name
    at getBrandCustomChannelName (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:22:11)
    at inject (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:54:24)
    at /home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:639:28)
    at EventEmitter.emit (node:events:520:28)
    at Client.next (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/loader.js:124:9)
    at Object.onceWrapper (node:events:639:28)
Error: Unsupported brand channel name
    at getBrandCustomChannelName (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:22:11)
    at inject (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugins/game.js:54:24)
    at /home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:639:28)
    at EventEmitter.emit (node:events:520:28)
    at Client.next (/home/runner/Minecraft-bot/node_modules/mineflayer/lib/loader.js:124:9)
    at Object.onceWrapper (node:events:639:28)
`

**Comment by u9g** [comment] 2022-03-24 23:39
what mc version is the server? & what mineflayer version?

**Comment by VaibhavVerma21** [comment] 2022-03-25 10:26
> what mc version is the server? & what mineflayer version?

The server is a fabric 1.18.2 and how can I check the mineflayer version?
It's on repl bte

**Comment by VaibhavVerma21** [comment] 2022-03-25 12:19
> what mc version is the server? & what mineflayer version?

Not sure but i think it is 3.18 You got any commands to check what is the version?

**Comment by SzczurekYT** [comment] 2022-03-27 18:52
I also had similar issues. I was using wrong password. Also make sure you are using email as username, not you minecraft nickname.

**Comment by VaibhavVerma21** [comment] 2022-03-28 23:58
> I also had similar issues. I was using wrong password. Also make sure you are using email as username, not you minecraft nickname.

Have made sure

**Comment by u9g** [comment] 2022-04-01 02:42
So what's the problem now?

**Comment by xViada** [comment] 2022-04-02 14:52
I have exactly the same problem as you, I can't find a solution

**Comment by dustcloud777** [comment] 2022-04-18 00:04
Same issue, but my config didn't have the password in the first place. it did use microsoft auth as well though

**Comment by extremeheat** [comment] 2022-04-18 00:14
The problem here has nothing to do with ms auth. 

If you have actual authentication problems I suggest changing username and removing the password field and if that does not work,

 Log out of the launcher, log in again with your account and repeat the step above with your code. 
 
If it still doesn’t work you can ask a specific question with detailed information with information about any errors on the discord on in a discussion

**Comment by dustcloud777** [comment] 2022-04-18 01:05
> The problem here has nothing to do with ms auth. For this error I suggest to try connecting to a different Minecraft server

Wish I could, this doesn't really seem to be an option. I get the same error when connecting to my own computer

> If you have actual authentication problems I suggest changing username and removing the password field and if that does not work,

I've done this
 
> Log out of the launcher, log in again with your account and repeat the step above with your code.

This part too, I'm pretty sure 

> If it still doesn’t work you can ask a specific question with detailed information with information about any errors on the discord or in a discussion

Well, this is my error:
```
Error: Unsupported brand channel name
    at getBrandCustomChannelName (C:\Users\user\node_modules\mineflayer\lib\plugins\game.js:22:11)
    at inject (C:\Users\user\node_modules\mineflayer\lib\plugins\game.js:54:24)
    at C:\Users\user\node_modules\mineflayer\lib\plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (C:\Users\user\node_modules\mineflayer\lib\plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (C:\Users\user\node_modules\mineflayer\lib\plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:641:28)
    at EventEmitter.emit (node:events:527:28)
    at next (C:\Users\user\node_modules\mineflayer\lib\loader.js:124:9)
    at Object.createBot (C:\Users\user\node_modules\mineflayer\lib\loader.js:105:34)
```
I've already authed the account for microsoft. This is my createBot call

```
 var botConfig = {
        viewDistance: 2,
        username: "NEBULA",  
        keepAlive: true,
        host: "paper.velocityserver", not the actual ip
        version: "1.18.2",       
        physicsEnabled: true, 
        auth: "microsoft"
    }
var bot = mineflayer.createBot(botConfig)
```

**Comment by SzczurekYT** [comment] 2022-04-18 07:10
> This is my createBot call
> 
> ```
>  var botConfig = {
>         viewDistance: 2,
>         username: "NEBULA",  
>         keepAlive: true,
>         host: "paper.velocityserver", not the actual ip
>         version: "1.18.2",       
>         physicsEnabled: true, 
>         auth: "microsoft"
>     }
> var bot = mineflayer.createBot(botConfig)
> ```

Try to use email instead of nickname.

**Comment by nickelpro** [comment] 2022-04-18 07:20
It's got nothing to do with authentication.

The problem is that `bot.supportFeatures` isn't returning the correct information for the brand channel. The most likely reason for that is needing to update minecraft-data. Minecraft data supports the correct channel prefixing information for all versions (https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/features.json#L48-L56) so the only way to get this error is to be using a minecraft-data version that is older than the version of minecraft you're targeting.

**Comment by nickelpro** [comment] 2022-04-18 07:20
Recommend closing @u9g

**Comment by u9g** [comment] 2022-04-18 07:29
Just uninstall mineflayer and reinstall it. then ensure you are on the latest version (currently 4.3.0), then try your code again and it will run fine.

**Closed** 2022-04-18 07:29 UTC

**Comment by YableZhao** [comment] 2022-12-29 12:30
> 

This helps!
