### ISSUE TITLE
Server rejects Transaction while Crafting

### ISSUE THREAD

**Issue by MrKinauJr** [PrismarineJS/mineflayer#1112] opened 2020-07-05 12:46 UTC
[X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.22.0
 - server: spigot 1.15.2
 - node: 14.3.0

## Detailed description of a problem
The Server rejects the Transaction while crafting a Iron Axe.

## Current code
```js
crafting_bench = bot.blockAt(v(-12,60,-151)) // Crafting Bench
iron_axe_recipe = bot.recipesFor(522,null,1,crafting_bench)[0] // First Recipe for a iron_axe
bot.craft(iron_axe_recipe,1,crafting_bench,(err)=>{
    console.log(err)
})
```

## Expected behavior
It should not reject the Transaction and craft the iron axe.

## Additional context
I don't know if it's relevant but i get the items from a chest first. That should not interfere with crafting though. I've read through some of the fixed Issues and they all seemed that they got fixed by adding a delay. This sadly did not fix my Problem. 

I have provided the Recipe incase it helps debugging.
```js
Recipe {
  result: RecipeItem { id: 522, metadata: undefined, count: 1 },
  inShape: [
    [ [RecipeItem], [RecipeItem] ],
    [ [RecipeItem], [RecipeItem] ],
    [ [RecipeItem], [RecipeItem] ]
  ],
  outShape: null,
  ingredients: null,
  delta: [
    RecipeItem { id: 545, metadata: null, count: -2 },
    RecipeItem { id: 530, metadata: null, count: -3 },
    RecipeItem { id: 522, metadata: undefined, count: 1 }
  ],
  requiresTable: true
}
```

**Comment by MrKinauJr** [comment] 2020-07-07 00:14
I added some more Craft Functions in my Code. It seems it bugs with a Hopper too. But with a chest it works flawlessly. It might be due to multiple Resources used? In the issues it seems adding a delay helped. Does the craft.js plugin has a delay when crafting?

**Comment by Slord6** [comment] 2020-07-07 17:37
I am also experiencing the same problem.

mineflayer: 2.22.1
server: vanilla 1.15.2
node: 12.14.1

It's reproducable with the `inventory.js` example. I've tried the simplest recipes I can think of; torch, stone pick and oak planks, none of which work. Happens with and without crafting table.

Stack trace:

```
Error: Server rejected transaction.
    at Bot.<anonymous> (D:\samlo\Documents\mineflayer\node_modules\mineflayer\lib\plugins\inventory.js:550:12)
    at Object.onceWrapper (events.js:300:26)
    at Bot.emit (events.js:210:5)
    at onRejected (D:\samlo\Documents\mineflayer\node_modules\mineflayer\lib\plugins\inventory.js:506:11)
    at confirmTransaction (D:\samlo\Documents\mineflayer\node_modules\mineflayer\lib\plugins\inventory.js:489:7)
    at Client.<anonymous> (D:\samlo\Documents\mineflayer\node_modules\mineflayer\lib\plugins\inventory.js:593:5)
    at Client.emit (events.js:210:5)
    at FullPacketParser.<anonymous> (D:\samlo\Documents\mineflayer\node_modules\minecraft-protocol\src\client.js:88:12)
    at FullPacketParser.emit (events.js:210:5)
    at addChunk (D:\samlo\Documents\mineflayer\node_modules\readable-stream\lib\_stream_readable.js:298:12)
```

**Comment by Slord6** [comment] 2020-07-07 18:19
Just checked in minecraft 1.16.1 with mineflayer version 2.23.0 with the same result

**Comment by rom1504** [comment] 2020-07-07 18:42
Can you reproduce with older minecraft versions ?

**Comment by Slord6** [comment] 2020-07-07 19:41
Doesn't look like it. `1.12` seems to work as expected, as does `1.14.2`

**Comment by rom1504** [comment] 2020-07-08 07:15
Ok it's possible something wasn't updated properly in 1.15 and 1.16
regarding crafting then.
That's weird because we have tests for crafting.
I'll have a look later

**Comment by Slord6** [comment] 2020-07-09 16:55
I've just re-checked with minecraft version 1.14 specifically checking torches, giving the bot sticks coal and charcoal and get the same error. So could well be that the issue is older

**Comment by Slord6** [comment] 2020-07-19 10:55
@rom1504 were you able to track down the cause for this?

**Comment by rom1504** [comment] 2020-07-19 11:11
No, feel free to work on it

**Comment by Slord6** [comment] 2020-07-19 16:11
Bit out of my depth, but had a look. The problem could be that recipes are being put in upside-down, possibly?

If I give the bot iron ingots and ask it to create an iron helmet the server rejects the transaction, but if I then break the crafting table, a minecart pops out. This could also explain wh,y for example, crafting iron ingots into iron blocks and visa-versa works, but crafting a torch doesn't. Similarly, unshaped crafting like a book works, as does bookshelf, which is the same upside-down as the right way up.

**Comment by Slord6** [comment] 2020-07-19 17:21
I can confirm that's definitely the issue. I don't know where that fix needs to happen though, otherwise I'd put in a PR.

**Comment by rom1504** [comment] 2020-07-19 18:19
https://github.com/PrismarineJS/prismarine-recipe and/or https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/craft.js

**Comment by rom1504** [comment] 2020-08-30 17:31
duplicate of https://github.com/PrismarineJS/minecraft-data/issues/231

**Closed by rom1504** 2020-08-30 17:31 UTC
Labels: possible bug
