### ISSUE TITLE
How to make the bot don't change its view while digging?

### ISSUE THREAD

**Issue by Denaryplanet** [PrismarineJS/mineflayer#1303] opened 2020-09-10 10:48 UTC
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.12.2
 - node: 12.18.3

## Clear question
How to prevent the bot from changing its gaze when digging?
## What did you try yet?

bot.dig()
I used the method bot.dig(block,forceLook=false), but it didn't help to remove the change of view. What have I done wrong ?

## Your current code

Please put here any custom code you tried yet.

```js

bot.dig(block)

```

## Additional context

**Comment by Karang** [comment] 2020-09-17 19:54
duplicate of https://github.com/PrismarineJS/mineflayer/issues/1318

**Closed by Karang** 2020-09-17 19:54 UTC
Labels: question
