### ISSUE TITLE
cannot read property 'accessToken' of undefined

### ISSUE THREAD

**Issue by RileyDatLord** [PrismarineJS/mineflayer#650] opened 2018-03-09 08:40 UTC
Code>
```js
var mineflayer = require('mineflayer');
var path = require('path');

if(process.argv.length !== 5) {
  console.log("Usage : node session.js <host> <port> <pathToLauncherProfiles>");
  process.exit(1);
}

var profile = require(path.resolve(process.argv[4], 'launcher_profiles.json'));
var auth = profile.authenticationDatabase[profile.selectedUser];

var session = {
  accessToken: auth.accessToken,
  clientToken: profile.clientToken,
  selectedProfile: {
    id: auth,
    name: auth.displayName
  }
};

var bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  session: session
});

bot.once('login', function() {
  console.log('loged in');
  bot.quit();
});
```
Error>
```js
PS C:\Users\Riley\Desktop\code\minecraft-bot> node . minehut.com 25545 C:\Users\Riley\AppData\Roaming\.minecraft\
C:\Users\Riley\Desktop\code\minecraft-bot\index.js:13
  accessToken: auth.accessToken,
                    ^

TypeError: Cannot read property 'accessToken' of undefined
    at Object.<anonymous> (C:\Users\Riley\Desktop\code\minecraft-bot\index.js:13:21)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3```

**Comment by rom1504** [comment] 2018-03-09 09:28
Yes, fix your file content or your code. The error happening here is
unrelated with mineflayer

**Comment by RileyDatLord** [comment] 2018-03-09 09:46
Error still happens in a different folder (one with only modules: Path, and Mineflayer)

**Comment by rom1504** [comment] 2018-03-09 13:30
Yes the problem is in your json file or your code.

**Comment by rom1504** [comment] 2018-04-30 11:00
should be fixed with recent merge

**Closed** 2018-05-01 19:26 UTC
