### ISSUE TITLE
Cannot Connect To "noxiouspvp.com"

### ISSUE THREAD

**Issue by JustinKelleher** [PrismarineJS/mineflayer#618] opened 2017-12-24 01:02 UTC
I can get my bot to work on all servers, except on "noxiouspvp.com" where I get the error listed below.

**Error**:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Inflate.zlibOnError (zlib.js:153:15)

**Comment by rom1504** [comment] 2018-01-01 22:12
duplicate of https://github.com/PrismarineJS/mineflayer/issues/431

**Closed by rom1504** 2018-01-01 22:12 UTC
