### ISSUE TITLE
How to dig in a 5 block generator in the direction of sight?

### ISSUE THREAD

**Issue by gropard** [PrismarineJS/mineflayer#1308] opened 2020-09-11 11:28 UTC
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.12.2
 - node: 12.18.3

## Clear question

How to dig in a 5 block generator with an efficiency of 8?
I do not understand how to dig in the direction the bot is looking and dig those blocks.

Can I have an example? Otherwise, it doesn't come as more than 1 block to dig by sight, and even quickly
## What did you try yet?

bot.dig()
bot.blockInsight()

## Your current code

Please put here any custom code you tried yet.

```js
bot.dig()

```

## Additional context
And also when I tried to dig 1 block, this block broke more slowly than with minecraft

**Comment by Karang** [comment] 2020-09-11 11:39
duplicate of https://github.com/PrismarineJS/mineflayer/issues/1302 and https://github.com/PrismarineJS/mineflayer/issues/1307

**Closed by Karang** 2020-09-11 11:39 UTC
Labels: question
