### ISSUE TITLE
Click on npc

### ISSUE THREAD

**Issue by Systemwartung** [PrismarineJS/mineflayer#924] opened 2020-03-24 10:37 UTC
I want to click on an npc but it doesn't works what I have to do that I can click on a NPC

**Comment by wvffle** [comment] 2020-03-24 11:50
Duplicate of #826

**Closed by wvffle** 2020-03-24 11:50 UTC

**Comment by Systemwartung** [comment] 2020-03-24 11:58
There is no reason I want to know Ho I can click on a npc can you pleas send me the code
