### ISSUE TITLE
Autofishing not work

### ISSUE THREAD

**Issue by Liaraswd** [PrismarineJS/mineflayer#697] opened 2018-08-01 15:41 UTC
**This code for auto fishing,**
But it does not work. Please tell me how to fix it.

This is use for throw a bait `bot.equip(bot.inventory.findInventoryItem(346), 'hand', bot.activateItem)`

This is event for catch it
`bot.on('soundEffectHeard', function(soundName) {
    if (soundName === 'random.splash') {
        bot.chat("Success")
        setTimeout(bot.activateItem, 500)
    }
})`

**Comment by plexigras** [comment] 2018-08-01 18:35
duplicate of https://github.com/PrismarineJS/mineflayer/issues/695

**Closed by plexigras** 2018-08-01 18:35 UTC
