### ISSUE TITLE
bot.game.dimension returns the dimension the bot logged on instead of the current one

### ISSUE THREAD

**Issue by japa4551** [PrismarineJS/mineflayer#1817] opened 2021-03-29 03:58 UTC
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.4.0
 - mineflayer-pathfinder: 1.6.1
 - node: 14.15.3

## Detailed description of a problem
Every time i try to print the bot's current dimension with bot.game.dimension it instead prints the dimension the bot logged in, no matter what dimension im in.

## Your current code
```js
/*
var = mineflayer.createBot()

const playerFilter = (entity) => entity.type == "player"
var bot_current_position = `${Math.round(bot.entity.position.x)} ${Math.round(bot.entity.position.y)} ${Math.round(bot.entity.position.z)}`

var bot_nearest_player = bot.nearestEntity(playerFilter)

console.log(The bot has been killed at ${bot_current_position} by ${bot_nearest_player.username} on dimension ${bot.game.dimension})
*/
```

## Additional context
Another user was also having this problem, he mentioned that the problem happend for him before the "Karangs world refactor".

**Comment by u9g** [comment] 2021-04-05 03:05
duplicate of https://github.com/PrismarineJS/mineflayer/issues/1705

**Closed** 2021-04-12 17:29 UTC
Labels: Stage1, possible bug
