### ISSUE TITLE
Movement issues with fences, other obstructing blocks

### ISSUE THREAD

**Issue by zubearc** [PrismarineJS/mineflayer#1131] opened 2020-07-11 04:20 UTC
[ x ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

Ran into an odd issue with getting the bot moving. When setControlState is set to forward, the bot seems to get stuck when walking over fences in the ground. I thought this may be due to the fence bounding box colliding with the player BB, however even after changing the fence bounding box data the bot still gets stuck when getting close to the fence. Placing a slab over the fence allows the bot to walk through.
 
https://i.imgur.com/rPUpnbW.png

Some other questions:
- Is it possible to autojump when `setControlState("forward", true)` is set? Setting entity.jumpQueued in prismarine-physics when `entity.isCollidedHorizontally` and `entity.isCollidedVertically` seems like it works, but it still gets stuck on the fence oddly.

**Comment by Karang** [comment] 2020-07-11 14:19
I can confirm the bug. This needs to be fixed in https://github.com/PrismarineJS/prismarine-physics
Fences are a special block because their bounding box goes outside of the block, maybe that needs special code, but it's not obvious to me why it doesn't work.
It needs some advanced debugging, feel free to continue the invesigations. Here are some references material: https://www.mcpk.wiki/wiki/SourceCode

For the autojump: you can try setting bot.physics.stepHeight to 1.

**Comment by zubearc** [comment] 2020-07-12 02:45
Thanks. After hunting around, I found two issues.

One, when the bot is standing on a fence the bot has a tenancy to fall through the fence because it doesn't properly check for the bounding box of the fence under it. Fixed by changing a line in getSurroundingBBs in prismarine-physics 
`    for (cursor.y = Math.floor(queryBB.minY); cursor.y <= Math.floor(queryBB.maxY); cursor.y++) {` to
`    for (cursor.y = Math.floor(queryBB.minY) - 1; cursor.y <= Math.floor(queryBB.maxY); cursor.y++) {`. Not fixing this causes a infinite loop between the server teleporting the bot and the bot resending invalid SetPosition packets.

Also, the bounding box for a fence seems to be different depending on block state (connected vs unconnected), it doesn't seem like this accounted for right now.

**Comment by Karang** [comment] 2020-07-12 07:36
The -1 seems to fix the main issue indeed :) Could you make a PR in https://github.com/PrismarineJS/prismarine-physics ?

The problem with the block state is known, but should only be there for versions <1.13 (before the shape depended not only on the state but also on the surrounding blocks, so the client need to compute that, and we don't). For versions >1.13 the shape depends only on the block state (that encode the connections as well) and so is set properly by the server so we shouldn't have an issue.

**Comment by zubearc** [comment] 2020-07-12 08:27
Done. I'm using mineflayer for an AI project with Microsoft/Malmo which only supports 1.8/1.11 so I'm gonna have to figure out a way to make it work. But the fences issue seems to be fixed, yeah.

**Closed** 2020-07-12 13:47 UTC
Labels: physics, possible bug
