### ISSUE TITLE
Is it possible to switch between vanilla client and mineflayer bot (without login / logout)?

### ISSUE THREAD

**Issue by ahibbe** [PrismarineJS/mineflayer#728] opened 2018-10-16 07:33 UTC
Although I do not believe that this is possible, but maybe there is still a chance. In my case, it's quite difficult (for a bot) to get to a certain location on a non vanilla server and then let the bot do things automatically. Is it possible to navigate with the vanilla client to this place and then switch to the bot via mineflayer (without login / logout)?

**Comment by plexigras** [comment] 2018-10-16 13:15
you use a proxy like [this](https://github.com/PrismarineJS/mineflayer/issues/315#issuecomment-343660526) and instead of having `keepAlive` disabled you enable/remove it from the `createBot` options.

if you still have issues you might try to figure out if it is due to the minecraft client sending any packages you want to filter out. `client.on('data', console.log)` should help.

**Comment by ahibbe** [comment] 2018-10-24 06:50
Thanks for your answer, the proxy thing works great. I can use the keyboard-driven client to go to a location that is not easy to reach and then close the client and then use client.on ("end" ..) as the starting point for automated actions.


For these actions, it would be helpful if the physics plugin were now active again. We deliberately did not load this on createBot with plugins: {physics: false}, as this would not work with a connected client. Now the client is closed and the physics plugin could be activated.

My question:
Is there a way to load the physics plugin later?

Unfortunately, all my attempts have failed.

Thank you

**Comment by plexigras** [comment] 2018-10-24 10:09
the physics module causes some glitchiness but i think having it disabled is not necessary.

i believe you should also be able to load it later using

```js
bot.loadPlugin(require('mineflayer/lib/plugins/physics'))
```

**Comment by piousdeer** [comment] 2018-10-27 13:33
Is there a way to do this with a real server, not with prismarine? It keeps kicking me no matter what I try.

**Comment by plexigras** [comment] 2018-10-27 13:43
did you try this?

https://github.com/PrismarineJS/mineflayer/issues/315#issuecomment-409931101

**Comment by piousdeer** [comment] 2018-10-27 13:52
In lluiscab's code `client` is generated by NMP server, I'm trying to connect to a normal Spigot server.

**Comment by plexigras** [comment] 2018-10-27 14:02
i'm not sure what you are trying to do, the nmp server is just a proxy server.

**Comment by piousdeer** [comment] 2018-10-27 14:09
I'm trying to get a mineflayer bot to connect to a Spigot server while I'm also connected with a normal vanilla client. So that I and my bot end up "controlling the same body". Now that I think of it it's probably impossible.

**Comment by rom1504** [comment] 2018-11-04 14:06
duplicate of https://github.com/PrismarineJS/mineflayer/issues/315 , please continue there

**Closed by rom1504** 2018-11-04 14:06 UTC
