### ISSUE TITLE
Update to 1.19?

### ISSUE THREAD

**Issue by Jish-The-Third** [PrismarineJS/mineflayer#2714] opened 2022-07-27 02:59 UTC
I was thinking, I am kind of new to AI and machine learning.

I was working on a bot, could you guys possibly update to 1.19?

![image](https://user-images.githubusercontent.com/100040996/181151208-3af21677-7e7a-4846-b7cb-f1978b05d2c0.png)

**Comment by amoraschi** [comment] 2022-07-27 08:34
Duplicate of #2668

**Closed** 2022-07-27 08:52 UTC
Labels: new feature, Stage1
