### ISSUE TITLE
Bot does not detect entities that get in a boat

### ISSUE THREAD

**Issue by TooterTutor** [PrismarineJS/mineflayer#3035] opened 2023-04-25 17:34 UTC
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 1.19.2
 - server: vanilla 1.19.2
 - node: 19.4.0

## Detailed description of a problem
Bot cannot detect when an entity, such as a player gets into an object such as a boat. Same thing happens when getting out of the boat.
The `bot.on('entityAttach' (entity, vehicle) => {})` and `bot.on('entityDetach' (entity, vehicle) => {})`events do not fire at all.

## What did you try yet?
Yes. I tried the `entityAttach`, and the `entityDetach` events.
I tried the `chatterbox.js` example, and when I would get into a boat, nothing would fire in chat.

## Your current code
```js
bot.on("entityAttach", (entity, vehicle) => {
    if (entity.type === 'player' && vehicle.type === 'object') {
        bot.mount(vehicle)
    }
})
```

## Expected behavior
When a player gets into a boat, the bot will also get into the boat.

**Comment by extremeheat** [comment] 2023-05-01 17:26
Dupe of https://github.com/PrismarineJS/mineflayer/issues/2819

**Closed by extremeheat** 2023-05-01 17:26 UTC
Labels: possible bug, Stage1
