### ISSUE TITLE
Error causing bot to crash upon moving servers

### ISSUE THREAD

**Issue by 1by** [PrismarineJS/mineflayer#757] opened 2018-12-22 23:54 UTC
Alright so, this is sorta related to #677 
Tried this on versions: 1.8, 1.8.8, 1.8.9, 1.12.1,1.12.2, Server has their own custom spigot, 
Worked perfectly in the hub server, about 5 seconds after it moved to /server factions, it crashed with that error, Latest mineflayer version. All i expected it to do was stay on /server factions.

C:\Users\Seppe\node_modules\mineflayer\lib\plugins\inventory.js:390
    assert.ok(click.id <= actionId)
                    ^

TypeError: Cannot read property 'id' of undefined
    at confirmTransaction (C:\Users\Seppe\node_modules\mineflayer\lib\plugins\inventory.js:390:21)
    at Client.bot._client.on (C:\Users\Seppe\node_modules\mineflayer\lib\plugins\inventory.js:502:5)
    at Client.emit (events.js:182:13)
    at FullPacketParser.deserializer.on (C:\Users\Seppe\node_modules\minecraft-protocol\src\client.js:82:12)
    at FullPacketParser.emit (events.js:182:13)
    at addChunk (C:\Users\Seppe\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:301:12)
    at readableAddChunk (C:\Users\Seppe\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:283:11)
    at FullPacketParser.Readable.push (C:\Users\Seppe\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:247:10)
    at FullPacketParser.Transform.push (C:\Users\Seppe\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:149:32)
    at FullPacketParser._transform (C:\Users\Seppe\node_modules\protodef\src\serializer.js:85:10)

**Comment by rom1504** [comment] 2018-12-23 10:32
Can you turn on debug mode (see readme as to how) and report the packets ?

**Comment by 1by** [comment] 2018-12-23 10:57
d packet play.entity_teleport +3ms
  minecraft-protocol {
  minecraft-protocol   "entityId": 3555035,
  minecraft-protocol   "x": -1088,
  minecraft-protocol   "y": 2752,
  minecraft-protocol   "z": -736,
  minecraft-protocol   "yaw": -128,
  minecraft-protocol   "pitch": 0,
  minecraft-protocol   "onGround": false
  minecraft-protocol } +0ms
  minecraft-protocol read packet play.keep_alive +1ms
  minecraft-protocol {
  minecraft-protocol   "keepAliveId": 976
  minecraft-protocol } +0ms
  minecraft-protocol writing packet play.keep_alive +0ms
  minecraft-protocol { keepAliveId: 976 } +1ms
  minecraft-protocol read packet play.transaction +0ms
  minecraft-protocol {
  minecraft-protocol   "windowId": 0,
  minecraft-protocol   "action": 976,
  minecraft-protocol   "accepted": false
  minecraft-protocol } +1ms
C:\Users\Seppe\node_modules\mineflayer\lib\plugins\inventory.js:390
    assert.ok(click.id <= actionId)
                    ^

TypeError: Cannot read property 'id' of undefined


This is what happened when i debugged it

**Comment by 1by** [comment] 2018-12-23 16:08
https://gyazo.com/657bddc90de42766235b6b62fd12d738 this is exactly what happens when the bot goes from hub to factions.

**Comment by rom1504** [comment] 2018-12-23 16:15
Can you report the full debug log (put it on gist for example), there's
probably information about why that happens.

**Comment by 1by** [comment] 2018-12-23 16:19
https://gist.github.com/1by/1dc36b26b9ac4d4ec19a7cbcca61ff33
This is all it would let me copy, hope it helps!

**Comment by rom1504** [comment] 2018-12-24 19:03
Yes most likely this is caused by something different your server is doing
with inventory and mineflayer is not handling it.
Try changing inventory.js

**Comment by rom1504** [comment] 2019-08-22 22:30
now fixed

**Closed by rom1504** 2019-08-22 22:30 UTC
Labels: non-vanilla
