### ISSUE TITLE
bot crash in water (beginning of solution)

### ISSUE THREAD

**Issue by docteur-turboss** [PrismarineJS/mineflayer#2854] opened 2022-12-05 20:34 UTC
- [ no] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: vanilla 1.19
 - node: 19.2.0
## Detailed description of a problem
Hello,
I think I have found something about the problem of the bot that crashes when we put it in the water in 1.19.

Recently, I started to approach your module, after several tries and tests I noticed that the bot starts to crash when it is in the water.
So I started to look for the different modules until I used only one, this one, so I logged all the possibilities, and in the playerUpdated vent of the client.on, I had a rather surprising result. (to avoid problems I have released some details of the results).

```
entity: Entity {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    id: 1695,
    position: Vec3 { x: -82.5, y: 68, z: -15.5 },
    velocity: Vec3 { x: 0, y: -0.0784000015258789, z: 0 },
    yaw: 3.141592653589793,
    pitch: 0,
    onGround: true,
    height: 1.62,
    width: 0,
    effects: {},
    equipment: [ <5 empty items> ],
    heldItem: null,
    isValid: true,
    metadata: [
      0,     300,      undefined,
      false, false,    false,
      0,     0,        0,
      20,    0,        false,
      0,     0,        undefined,
      0,     0,        127,
      1,     [Object], [Object]
    ],
    username: 'blblblblblb',
    type: 'player',
    name: 'player',
    timeSinceOnGround: 0,
    isInWater: false,
    isInLava: false,
    isInWeb: undefined,
    isCollidedHorizontally: false,
    isCollidedVertically: true,
    attributes: { 'minecraft:generic.movement_speed': [Object] },
    [Symbol(kCapture)]: false
  }
  ``` 
in this result, we can see isInWater: false, while it is in a water block, and just after a kick error message : 
{"translate": "multiplayer.disconnect.invalid_player_movement"} true,
So, I appeal to you to fix this bug, I look on my side to see where it can be fixed, but for me, I don't think it comes from my little log code.

sorry for derangment, see you soon

## Your current code
```js

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'MyServer', 
  username: 'blblblblblb', 
  port: 'MyPort' 
  })

bot.on('playerUpdated', (player)=>{
    console.log(player)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)

```

## Expected behavior
A check of this problem for other user, I can help if needed.

## Additional context
test of a bot in water and on water block

thanks

**Comment by Huoyuuu** [comment] 2022-12-06 07:09
Hi, I also encountered the same problem, and I'd like to add some details: when the bot is kicked out, **"isInWater" is true**, and I think the key problem is that when the bot encounters the fluid, **its y coordinate and the velocity in the y axis direction are NaN**.

The following are the specific data and related codes.

```JS
bot.on('kicked', (reason) => {
    console.log(bot.entity)
    console.log(reason)
})
```

```
Entity {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: 10224,
  position: Vec3 { x: -0.5, y: NaN, z: 20.5 },
  velocity: Vec3 { x: 0, y: NaN, z: 0 },
  yaw: 3.141592653589793,
  pitch: 0,
  onGround: false,
  height: 1.62,
  width: 0,
  effects: {},
  equipment: [ <5 empty items> ],
  heldItem: null,
  isValid: true,
  metadata: [ <1 empty item>, 299, <15 empty items>, 127 ],
  username: 'bot',
  type: 'player',
  name: 'player',
  timeSinceOnGround: 0,
  isInWater: true,
  isInLava: false,
  isInWeb: undefined,
  isCollidedHorizontally: false,
  isCollidedVertically: true,
  attributes: {
    'minecraft:generic.movement_speed': { value: 0.10000000149011612, modifiers: [] }
  },
  [Symbol(kCapture)]: false
}
```

**Comment by Huoyuuu** [comment] 2022-12-07 16:25
[#2849](https://github.com/PrismarineJS/mineflayer/issues/2849)

**Comment by extremeheat** [comment] 2022-12-10 05:51
Known issue in 1.19, dupe of https://github.com/PrismarineJS/mineflayer/issues/2796

**Closed by extremeheat** 2022-12-10 05:51 UTC
Labels: possible bug, Stage1
