### ISSUE TITLE
When digging, a bot sometimes dramatically changes sight 

### ISSUE THREAD

**Issue by Denaryplanet** [PrismarineJS/mineflayer#1329] opened 2020-09-23 10:18 UTC
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: spigot 1.13.2
 - node: 12.18.4

## Clear question
When digging, a bot sometimes dramatically changes sight, this destroys the generator. What could be the problem with a sudden change of sight?
## What did you try yet?

bot.dig()
bot.blockinsight()
bot.lookAt()

## Your current code

```js

const dig = () => {
	if (digging == 1 ) {
		if (bot.targetDigBlock) {
			setTimeout(dig, 1)
			return
		}else{
			var target = bot.blockInSight()
			if (target !== undefined && target.position.distanceTo(bot.entity.position.offset(0,1,0)) > 5.6) {
				target = undefined
			};
			if (target !== undefined) {
				bot.lookAt(target.position)
				bot.dig(target,() => setTimeout(dig, 1));
			}else{
				setTimeout(dig, 1)
				return
			}
		}
	}
};


```

## Additional context

**Comment by rom1504** [comment] 2020-09-23 11:44
https://github.com/PrismarineJS/mineflayer/issues/1318 duplicate of this one
Please reread the answers there

**Closed by rom1504** 2020-09-23 11:44 UTC
Labels: question

**Comment by Denaryplanet** [comment] 2020-09-23 13:32
> #1318 duplicate of this one
> Please reread the answers there

wait, so what could be the problem? why is this happening ???
