### ISSUE TITLE
mcpe and minecraft windows 10 support

### ISSUE THREAD

**Issue by svilex** [PrismarineJS/mineflayer#374] opened 2016-02-13 13:10 UTC
is this bot supporting mcpe and mc windows 10 edition ?

**Comment by rom1504** [comment] 2016-02-13 13:12
no, this requires mcpe protocol support, see https://github.com/PrismarineJS/node-minecraft-protocol/issues/235

**Comment by rom1504** [comment] 2017-01-23 14:09
pocket-minecraft-protocol is almost working.
Hopefully we can merge it with nmp soon enough.

Now that mineflayer has some cross version support, it could be considered.

**Comment by rom1504** [comment] 2020-08-30 17:40
duplicate of https://github.com/PrismarineJS/mineflayer/issues/842

**Closed by rom1504** 2020-08-30 17:40 UTC
Labels: protocol support
