### ISSUE TITLE
Error: Deserialization error for play.toClient : Chunk size is 14 but only 2 was read [object ArrayBuffer]

### ISSUE THREAD

**Issue by officialmrohio** [PrismarineJS/mineflayer#631] opened 2018-01-15 04:26 UTC
I keep getting this error message when connecting to a server. It will connect for a moment and then crashes. Any ideas?
http://prntscr.com/i0jj49

**Comment by rom1504** [comment] 2018-01-15 11:41
It means one packet wasn't read to the end.

There's 2 things to fix here:
* Actually display the buffer and not [object]
* Display the packet id (the decompressor already got it, there must be
some way to propagate it to the error)

I'll do that.

However one question : which server gets you that error ?

**Comment by rom1504** [comment] 2018-01-15 12:13
Ah actually it's even simpler. When that error is emitted, we have the
(probably partial) parsed object, so we can just add that in the error to
know which packet has a problem.

Well I'll do these 2 things tonight and you can check again.

**Comment by officialmrohio** [comment] 2018-01-17 00:41
I have no idea what your saying @rom1504 because im not really a coder. Every bit of code there was written by someone else. But if you could fix it I would be crazy happy.

**Comment by officialmrohio** [comment] 2018-01-17 03:14
server is : play.guardianskies.com

**Comment by rom1504** [comment] 2018-01-17 09:04
Ok, I'll have a look when I have time, hopefully today

**Comment by officialmrohio** [comment] 2018-01-19 05:30
any update @rom1504

**Comment by rom1504** [comment] 2018-01-25 19:37
@officialmrohio sorry for the waiting time, I've been busy
I made these changes.
Can you try again and report the new error ?

**Comment by rom1504** [comment] 2018-01-25 19:38
(run npm update before)

**Comment by MeWoody** [comment] 2018-01-27 14:23
I'm getting the same problem on non-vanilla servers, here's the error:

`Error: Deserialization error for play.toClient : Chunk size is 18 but only 10 was read ; partial packet : [object Object] ; buffer : 230047472e0100000000003c04666c617400
    at FullPacketParser._transform (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\protodef\src\serializer.js:78:15)
    at FullPacketParser.Transform._read (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at FullPacketParser.Transform._write (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at FullPacketParser.Writable.write (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Decompressor.ondata (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at Decompressor.emit (events.js:211:7)
    at addChunk (C:\Users\MYNAME\Desktop\AltCheckBot\node_modules\readable-stream\lib\_stream_readable.js:284:12)` 

I updated to the last version (npm update), did a fresh install of Mineflayer later aswell to see if that changed anything. It works on some servers, but I think either they are only compatible for 1.8 clients or they're vanilla.

**Comment by officialmrohio** [comment] 2018-02-02 05:42
I am still receiving same issue.

**Comment by Cranite** [comment] 2018-03-07 01:00
This is what I get when I console.log everything emitted on the error event... or about a single page of it. The bot will login and spawn but will disappear not long after and not emit end or kicked events, instead the entire program terminates so I think it's crashing altogether. I'm not sure how to fix this.

```
Bot Started!
Bot Connected!
ERROR! PartialReadError: Deserialization error for play.toClient.sound_effect.x : Read error for params.sound_effect.x :
 undefined
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! PartialReadError: Deserialization error for play.toClient.attach_entity.entityId : Read error for params.attach_e
ntity.entityId : undefined
Message: You have auto-accepted invitation from the following groups while you were away: Hue.
ERROR! PartialReadError: Deserialization error for play.toClient.entity_update_attributes.properties.0.modifiers.7.uuid
: Read error for params.entity_update_attributes.properties.0.modifiers.7.uuid : undefined
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! PartialReadError: Deserialization error for play.toClient.entity_equipment.item.unknown.default.nbtData.name : Re
ad error for params.entity_equipment.item.unknown.default.nbtData.name : Missing characters in string, found size is 35
expected size was 528
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! PartialReadError: Deserialization error for play.toClient.entity_equipment.item.unknown.default.nbtData.name : Re
ad error for params.entity_equipment.item.unknown.default.nbtData.name : Missing characters in string, found size is 35
expected size was 528
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! PartialReadError: Deserialization error for play.toClient.entity_equipment.item.unknown.default.nbtData.name : Re
ad error for params.entity_equipment.item.unknown.default.nbtData.name : Missing characters in string, found size is 35
expected size was 528
ERROR! Error: Deserialization error for play.toClient : Chunk size is
ERROR! PartialReadError: Deserialization error for play.toClient.entity_equipment.item.unknown.default.nbtData.name : Re
ad error for params.entity_equipment.item.unknown.default.nbtData.name : Missing characters in string, found size is 48
expected size was 528
```

**Comment by rom1504** [comment] 2018-05-01 19:44
duplicate of https://github.com/PrismarineJS/mineflayer/issues/624

**Closed by rom1504** 2018-05-01 19:44 UTC
Labels: bug
