### ISSUE TITLE
Getting the contents of a map

### ISSUE THREAD

**Issue by SenkJu** [PrismarineJS/mineflayer#714] opened 2018-08-26 17:05 UTC
Hey!
Is it possible to get the content of a filled_map as a Base64-String for example? If so, how can I do it?

Thanks.

**Comment by plexigras** [comment] 2018-08-26 17:08
duplicate of https://github.com/PrismarineJS/mineflayer/issues/583

**Closed by plexigras** 2018-08-26 17:08 UTC
