### ISSUE TITLE
Trim username in chat.js

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/mineflayer#369] opened 2016-02-09 03:08 UTC
I have tested the jumper script provided in the mineflayer and it appears that when this line is called "  target = bot.players[username].entity;" the script crashes because it is reading the email not the username.

**Comment by rom1504** [comment] 2016-02-09 06:19
What's the exact error your getting?

**Comment by mattweil** [comment] 2016-02-09 15:04
C:\Users\mweil\Desktop\eeBot\examples\jumper.js:27
  target = bot.players[username].entity;
                                ^

TypeError: Cannot read property 'entity' of undefined
    at Bot.<anonymous> (C:\Users\mweil\Desktop\eeBot\examples\jumper.js:27:33)
    at emitMany (events.js:108:13)
    at Bot.emit (events.js:182:7)
    at parseOldMessage (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:32:15)
    at parseJsonMessage7 (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:74:11)
    at parseJsonMessage (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:99:9)
    at Client.<anonymous> (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:113:5)
    at emitTwo (events.js:87:13)
    at Client.emit (events.js:172:7)
    at Parser.<anonymous> (C:\Users\mweil\Desktop\eeBot\node_modules\minecraft-protocol\dist\client.js:83:15)

**Comment by mattweil** [comment] 2016-02-09 15:06
Changing 
`  target = bot.players[username].entity;`
to
`  target = bot.players["accountname"].entity;;`
works but of course just a temporary fix

**Comment by rom1504** [comment] 2016-02-09 15:42
Can you console.log(username) ?
What kind of server are you using ? Does it have a custom chat plugin ?

**Comment by rom1504** [comment] 2016-02-09 15:44
Ah and can you try to do `bot._client.on('chat', function(packet) {console.log(packet);});` ?

**Comment by Gjum** [comment] 2016-02-09 15:47
@rom1504 the problem is when you log in with your email, `bot.username` is your email not your username.

**Comment by mattweil** [comment] 2016-02-09 15:53
`console.log(username)` is returning the username of the player giving the command
`bot._client.on('chat', function(packet) {console.log(packet);});` returns the following
`{ message: '{"extra":["\\u003c",{"color":"dark_red","text":"[account giving command]"},"\\u003e jump"],"text":""}',
  position: 0 }`

**Comment by rom1504** [comment] 2016-02-09 15:56
if it correctly read the username, then what's in bot.players, can you print it ?

**Comment by rom1504** [comment] 2016-02-09 15:58
> @rom1504 the problem is when you log in with your email, bot.username is your email not your username.
I always login with my email with mineflayer and didn't have that problem so...

**Comment by rom1504** [comment] 2016-02-09 16:00
this https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/entities.js#L317 is what adds players to bot.players, I can't see how would that be related to migrated accounts.

**Comment by mattweil** [comment] 2016-02-09 16:08
It is only functioning at all because I changed: `target = bot.players[username].entity;` to `target = bot.players["blyat"].entity;`

`  console.log(username)` returns the following
`  { username: '**bot**',
     ping: 0,
     uuid: 'xxxxxx',
     entity:
      Entity {
        id: 469887,
        type: 'player',
        position: [Object],
        velocity: [Object],
        yaw: 3.141592653589793,
        pitch: 0,
        onGround: true,
        height: 1.62,
        effects: {},
        equipment: [Object],
        heldItem: null,
        isValid: true,
        metadata: [Object],
        username: '**bot**',
        timeSinceOnGround: 7.198000000000002 } },`

`  console.log(bot.players)` returns
`  swiftdart5:
   { username: '**account giving command**',
     ping: 1,
     uuid: 'xxxx',
     entity:
      Entity {
        id: 74,
        type: 'player',
        position: [Object],
        velocity: [Object],
        yaw: 6.037748381117884,
        pitch: -0.9081166264282996,
        onGround: true,
        height: 1.62,
        effects: {},
        equipment: [Object],
        heldItem: [Object],
        isValid: true,
        metadata: [Object],
        username: '**account giving command**',
        uuid: 'xxxxx',
        dataBlobs: undefined,
        headYaw: 6.062292073724054 } } }

**Comment by rom1504** [comment] 2016-02-09 16:09
username is an object ???

**Comment by Gjum** [comment] 2016-02-09 16:11
It sounds like you are overriding `username` with something weird. Can you `console.log(bot.username)`?

**Comment by mattweil** [comment] 2016-02-09 16:15
It is only functioning at all because I changed: `target = bot.players[username].entity;` to `target = bot.players["blyat"].entity;`

`console.log(bot.username` returns the correct username of the bot.

It is functioning with that change I made above, I can't get responses with `target = bot.players[username].entity;` it simply crashes

**Comment by rom1504** [comment] 2016-02-09 16:21
is `account giving command` different from `username` ?
And is `username` (and not bot.username) really that object up there ? (it should be a string)

**Comment by mattweil** [comment] 2016-02-09 16:28
`console.log(username)` is returning the information regarding the bot.
`console.log(bot.players)` returns information of the account who is giving the command.
The account giving the command is _different_ from `username`

**Comment by mattweil** [comment] 2016-02-09 16:30
Here is a snippet of my jumper.js we are looking at, let me know if you need more information.
`bot.on('chat', function(username, message) {
  if(username === bot.username) return;
  target = bot.players["BOTNAMEACCOUNTNAME"].entity;
  bot._client.on('chat', function(packet) {console.log(packet);});
  console.log(bot.username)
  var entity;`

**Comment by rom1504** [comment] 2016-02-09 16:35
"console.log(username) is returning the information regarding the bot." this is the bug.

username should be an username.

I don't understand how this could happen based on what you are saying.

**Comment by mattweil** [comment] 2016-02-09 16:42
Err.... going back to your jumper.js provided in mineflayer, the following is the jumper.js being executed
Take not that "CommandGiver" is the account giving the bot commands and "BOT" is the mineflayer bot.

```
bot.on('chat', function(username, message) {
  if(username === bot.username) return;
  console.log(username)
  target = bot.players[username].entity;
  bot._client.on('chat', function(packet) {console.log(packet);});
  var entity;
```

returns:

`You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
CommandGiver
C:\Users\mweil\Desktop\eeBot\examples\jumper.js:28
  target = bot.players[username].entity;
                                ^

TypeError: Cannot read property 'entity' of undefined
    at Bot.<anonymous> (C:\Users\mweil\Desktop\eeBot\examples\jumper.js:28:33)
    at emitMany (events.js:108:13)
    at Bot.emit (events.js:182:7)
    at parseOldMessage (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:32:15)
    at parseJsonMessage7 (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:74:11)
    at parseJsonMessage (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:99:9)
    at Client.<anonymous> (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:113:5)
    at emitTwo (events.js:87:13)
    at Client.emit (events.js:172:7)
    at Parser.<anonymous> (C:\Users\mweil\Desktop\eeBot\node_modules\minecraft-protocol\dist\client.js:83:15)`

**Comment by rom1504** [comment] 2016-02-09 16:44
okay that makes more sense.
Can you do a `console.log(Object.keys(bot.players))` and tell me the difference between the usernames displayed and what's displayed by `console.log(username)` ?

**Comment by rom1504** [comment] 2016-02-09 16:44
(or just you know, put the actual results there, is your username so secret ?)

**Comment by mattweil** [comment] 2016-02-09 16:48
Meh, I try not to associate my username with my real name but its seems to be complicating it more so it's whatever.

jumper.js below
```
bot.on('chat', function(username, message) {
  if(username === bot.username) return;
  console.log(Object.keys(bot.players))
  console.log(username)
  target = bot.players[username].entity;
  bot._client.on('chat', function(packet) {console.log(packet);});
  var entity;
```
Below is the result, "bylat" is the bot, and "swiftdart5" is my account sending commands.
```
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
[ 'blyat', 'swiftdart5' ]
 swiftdart5
C:\Users\mweil\Desktop\eeBot\examples\jumper.js:29
  target = bot.players[username].entity;
                                ^

TypeError: Cannot read property 'entity' of undefined
    at Bot.<anonymous> (C:\Users\mweil\Desktop\eeBot\examples\jumper.js:29:33)
    at emitMany (events.js:108:13)
    at Bot.emit (events.js:182:7)
    at parseOldMessage (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:32:15)
    at parseJsonMessage7 (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:74:11)
    at parseJsonMessage (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:99:9)
    at Client.<anonymous> (C:\Users\mweil\Desktop\eeBot\node_modules\mineflayer\lib\plugins\chat.js:113:5)
    at emitTwo (events.js:87:13)
    at Client.emit (events.js:172:7)
    at Parser.<anonymous> (C:\Users\mweil\Desktop\eeBot\node_modules\minecraft-protocol\dist\client.js:83:15)
```

**Comment by Gjum** [comment] 2016-02-09 16:51
I think there's a space before the username, do we strip whitespace in chat.js?

**Comment by rom1504** [comment] 2016-02-09 17:09
Yeah we should probably .trim() the username. That doesn't happen with a vanilla server so @mattweil is probably using a server with a chat plugin. But it should be easy enough to support that behavior.

**Comment by Gjum** [comment] 2016-02-09 17:10
matt said it's spigot without additional chat plugins, but spigot itself modifies chat already IIRC.

**Comment by rom1504** [comment] 2016-02-09 17:21
@mattweil so what you can do until we fix it in https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/chat.js is just do `target = bot.players[username.trim()].entity;`

**Comment by mattweil** [comment] 2016-02-09 17:56
works great, thanks

**Comment by rom1504** [comment] 2016-02-09 18:24
Let's close it when the change has been made in chat.js too

**Comment by wvffle** [comment] 2019-05-16 08:31
Not relevant since current implementation doesn't catch spaces in usernames.

**Closed by wvffle** 2019-05-16 08:31 UTC
Labels: chat, non-vanilla
